<div class="vc_row wpb_row vc_inner row">
    <div class="one-third wpb_column col-sm-12" id="atencion-quejas">
        <div class="vc_column-inner ">
            <div class="wpb_wrapper">
                <div class="icon-box style5"><i class="soap-icon-message"></i>
                    <div class="description">
                        <h5>Para consulta o contacto envíenos un correo a  <strong>atencionaclientes@aussa.com.mx</strong>  y si tiene alguna queja, reporte o sugerencia para mejorar nuestro servicio envíenos un correo a  <strong>calidad@aussa.com.mx</strong></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



