<div>
    <h2>Autobuses de pasajeros en el estado de Sinaloa</h2>
    <div role="form" class="wpcf7" id="wpcf7-f681-p682-o1" lang="en-US" dir="ltr">
        <div class="screen-reader-response"></div>
        <form action="" method="post" class="wpcf7-form" novalidate="novalidate">
            <div style="display: none;">
                <input type="hidden" name="_wpcf7" value="681" />
                <input type="hidden" name="_wpcf7_version" value="4.2.2" />
                <input type="hidden" name="_wpcf7_locale" value="en_US" />
                <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f681-p682-o1" />
                <input type="hidden" name="_wpnonce" value="35a0dedf9e" />
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Nombre</label><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" /></span>
                    </div>
                    <div class="form-group">
                        <label>Email</label><span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" /></span>
                    </div>
                    <div class="form-group">
                        <label>Teléfono</label><span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false" /></span>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="form-group">
                        <label>Mensaje</label><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="8" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false" placeholder="Escribe tu mensaje..."></textarea></span>
                    </div>
                </div>
            </div>
            <div class="col-sms-offset-6 col-sm-offset-6 col-md-offset-8 col-lg-offset-9">
                <input type="submit" value="ENVIAR" class="wpcf7-form-control wpcf7-submit" />
            </div>
            <div class="wpcf7-response-output wpcf7-display-none"></div>
        </form>
    </div>
</div>