<div id="map1" style="width:100%;height:400px"></div>
    <script type="text/javascript">
        jQuery(document).ready( function() {
            jQuery("#map1").gmap3({
                map: {options: {center: [23.9240911,-106.89944],zoom: 7,mapTypeId: google.maps.MapTypeId.ROADMAP,mapTypeControl: true,navigationControl: true,scrollwheel: false,streetViewControl: true,draggable: true,}},marker:{values: [{latLng:[24.8050567,-107.493354]},{latLng:[22.9921531,-105.8721399]},{latLng:[23.9240911,-106.89944]},{latLng:[22.8456291,-105.9100538]},{latLng:[23.2468188,-106.4572966]}], options: {draggable: false }, }});
        });
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqXsJS5G5POkVNMoQxC0OpobuWUmiKkOg&callback=initMap"></script>
</div>