<div class="sucursales_contacto">
    <h1>Ubica tu sucursal más cercana</h1>
    <p>Obten la mejor experiencia de viajar con Auto Transportes Unidos de Sinaloa: viaja rápido y seguro, con operadores capacitados e instalaciones de calidad.  </p>
</div>
<div class="vc_row wpb_row vc_inner row">
    <div class="one-third wpb_column col-sm-4 sucursal-contacto">
        <h2 class="title-contacto">Matriz Culiacán</h2>
        <img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/sucursal-culiacan.jpg" class="sucursal-img" alt="Matriz Culiacán">
        <div class="col-md-12" id="info-sucursales">
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-address"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p> Alfonso G. Calderón Velarde S/N Local #15 Desarrollo urbano Tres Ríos Culiacán, Sinaloa C.P. 800200</p></div>
            </div>
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-phone"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p>01 (667) 761 29 00</p></div>
            </div>
        </div>
    </div>
    <div class="one-third wpb_column col-sm-4 sucursal-contacto">
        <h2 class="title-contacto">Sucursal La cruz</h2>
        <img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/sucursal-mazatlan.jpg" class="sucursal-img" alt="Sucursal La cruz">
            <div class="col-md-12" id="info-sucursales">
                <div class="col-md-12">
                    <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-address"></i></p></div>
                    <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p>Carretera maxipista km 89<br>La cruz de elota, Sinaloa</p></div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-phone"></i></p></div>
                    <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p>01 (696) 961 02 41</p></div>
                </div>
            </div>
        </ul> 
    </div>
    <div class="one-third wpb_column col-sm-4 sucursal-contacto">
        <h2 class="title-contacto">Sucursal Mazatlán</h2>
        <img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/sucursal-mazatlan.jpg" class="sucursal-img" alt="Sucursal El rosario">
        <div class="col-md-12" id="info-sucursales">
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-address"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p>Carretera internacional norte <br>KM 120 Mazatlán, Sinaloa</p></div>
            </div>
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-phone"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p>01 (669) 983 32 32</p></div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="one-third wpb_column col-md-offset-2 col-sm-4 sucursal-contacto">
        <h2 class="title-contacto">Sucursal El rosario</h2>
        <img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/sucursal-elrosario.jpg" class="sucursal-img" alt="Sucursal Escuinapa">
        <div class="col-md-12" id="info-sucursales">
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-address"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p> Luis Donaldo Colosio S/N Colonia Centro<br> El rosario, Sinaloa</p></div>
            </div>
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-phone"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p>01 (694) 114 02 46</p></div>
            </div>
        </div>
    </div>
    <div class="one-third wpb_column col-sm-4 sucursal-contacto">
        <h2 class="title-contacto">Sucursal Escuinapa</h2>
        <img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/sucursal-escuinapa.jpg" class="sucursal-img" alt="Sucursal Escuinapa">
        <div class="col-md-12" id="info-sucursales">
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-address"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p> Hidalgo y Morelos S/N Colonia Centro <br>Escuinapa, Sinaloa C.P. 82400</p></div>
            </div>
            <div class="col-md-12">
                <div class="col-md-2 col-sm-2 col-xs-2"><p class="iconos_sucursales_contacto"><i class="soap-icon-phone"></i></p></div>
                <div class="col-md-10 col-sm-10 col-xs-10" id="titulo-sucursales-contacto-p"><p>01 (695) 953 48 05</p></div>
            </div>
        </div>
    </div>
</div>