<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Galería Royal</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Galería</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="container container-galeria" >
	<div class="row contenido-galeria">
		<div class="col-md-7 img-principal-galeria">
			<div class="img-contenido">
				<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/portada.jpg" alt="">
			</div>
		</div>
		<div class="col-md-5 descripcion-galeria">
			<h2>AUS IRIZAR i6 VOLVO/SCANIA</h2>
			<ul>
				<li> Autobuses I6 Irizar</li>
				<li> Unidades con 44 asientos reclinables.</li>
				<li> Habilitadas con pantallas HD de alta definición  de 22”</li>
				<li> Toma corriente</li>
				<li> Servicio de Internet a bordo por WIFI</li>
				<li> Cabina asilada</li>
				<li> Baños amplios </li>
			</ul>
		</div>
	</div>
	<div class="row interiores-exteriores">
		<div class="col-md-5">
			<div class="row">
				<div class="col-md-12">
					<h2 class="title-galeria-inte-ext">Interiores</h2>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria1.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria1.jpg" alt=""/>	
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria2.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria2.jpg" alt=""/>	
						</div>
					</a> 
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria3.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria3.jpg" alt=""/>	
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria4.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria4.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria5.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria5.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria6.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria6.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria7.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria7.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group1" href="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria8.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/interiores/galeria8-1.jpg" alt=""/>
						</div>
					</a>
				</div>
			</div>
		</div>
		<div class="col-md-5 col-md-offset-2">
			<div class="row">
				<div class="col-md-12">
					<h2 class="title-galeria-inte-ext">Exteriores</h2>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria1.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria1.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria2.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria2.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria3.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria3.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria4.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria4.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria5.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria5.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria6.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria6.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria7.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria7.jpg" alt=""/>
						</div>
					</a>
				</div>
				<div class="col-md-3 col-xs-12 img-link">
					<a class="grouped_elements" rel="group2" href="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria8.jpg">
						<div class="gal-img">
							<img src="<?= Conectar::ruta_web()?>script/images/galeria/exteriores/galeria8.jpg" alt=""/>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="row" id="banner-youtube">
		<div class="col-md-12">
			<a href="https://www.youtube.com/channel/UCMjrKoXHvPgFUZJRcYE_ANA" target="_blank" title="Autotransportes unidos de sinaloa">
				<img src="<?= Conectar::ruta_web()?>script/img_autotransportes/banner-youtube.jpg" alt="">
			</a>
		</div>
	</div>
</div>
	
 <script>
	// $("a.grouped_elements").fancybox();
	var jQuery = jQuery.noConflict();
	jQuery("a.grouped_elements").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600, 
		'speedOut'		:	200, 
		'overlayShow'	:	false
	});
 </script>