<div class="search-box-wrapper">
	<div class="search-box container">
		<div class="search-tab-content">
			<div id="tipo-pago" class="">
					<div class="title">
						<h2>Selección de tipo de pago</h2>
					</div>
					<form role="search" action="">
						<div class="row">
							<div class="form-group col-sm-4 col-md-3 col-md-offset-1  " >
								<label class="checkbox-inline"><input type="checkbox"><img  src="<?= Conectar::ruta_web()?>script/images/img/visa_mc.svg "class="img-responsive" alt="Cinque Terre" width="140" height="236" ></label>
							</div>
							<div class="form-group col-sm-4 col-md-3  col-md-offset-1 ">
								
								<label class="checkbox-inline"><input type="checkbox"><img  src="<?= Conectar::ruta_web()?>script/images/img/2000px-American_Express_logo.png"class="img-responsive" alt="Cinque Terre" width="86" height="236" ></label>
							</div>
							<div class="form-group col-sm-4 col-md-3 col-md-offset-1 ">
								
								<label class="checkbox-inline"><input type="checkbox"><img  src="<?= Conectar::ruta_web()?>script/images/img/transfer-logo.png"class="img-responsive" alt="Cinque Terre" width="140" height="236" ></label>
								<label class=""><a href=""><u>¿CÓMO PAGAR CON TRANSFER?</u></a></label>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-sm-4 col-md-4 col-md-offset-2">
								<label class="checkbox-inline"><input type="checkbox"><img  src="<?= Conectar::ruta_web()?>script/images/img/PayPal.png "class="img-responsive" alt="Cinque Terre" width="140" height="236" ></label>
								<label class=""><a href=""><u>¿QUÉ ES PAYPAL?</u></a></label>
							</div>
							<div class="form-group col-sm-4 col-md-4 col-md-offset-2">
								
								<label class="checkbox-inline"><input type="checkbox"><img  src="<?= Conectar::ruta_web()?>script/images/img/auscard-logo.png"class="img-responsive" alt="Cinque Terre" width="140" height="236" ></label>
							</div>	
						</div>
						<div class="row">
							<div class=" form-group col-xs-6 col-md-4">
								<div class="title">
									<h2>Importe total a pagar</h2>
									<label>$157.50</label>
								</div>
							</div>	
							<div class="col-xs-6 col-md-4">
								<div class="title">
									<h2>USTED AHORRÓ</h2><label>$17.50</label>
								</div>
							</div>
							<div class="col-xs-6 col-md-4">
								<div class="title">
									<h2>MONTO A PAGAR</h2><label>$157.50</label>
								</div>
							</div>		
						</div>
				</form>
				<form role="search" action="" class="form-horizontal">
					<div class="form-group col-sm-4 col-md-3">
                        <h4 class="title">Número teléfonico</h4>
                        <input type="text" name="telefono" class="input-text full-width" placeholder="9999-99-99-99" />
                    </div>
				</form>				
			</div>
		</div>
	</div>
</div>