<div class="header-fondo-culiacan">
	<div class="">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Sucursal Culiacan</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Sucursales - Culiacan</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="mod_sucursal_culiacan">
	<div class="container" id="contenido-general-nosotros">
	<h1>CULIACAN</h1>
	<div class="row">
		<div class="col-md-5" id="contenido-nosotros-texto">
			<div class="texto">
				<p>Culiacán es una de las ciudades mas visitadas de Sinaloa por sus bellos alrededores, sus lugares históricos, por sus fiestas populares, sus artesanías y por sus costumbres y tradiciones. 
					 Culiacán oficialmente es conocido como Culiacán Rosales, es una ciudad que se encuentra ubicada al noroeste de México, capital y ciudad mas grande del estado de Sinaloa tiene una población de 755 510 habitantes (2010).
				</p>
				<p>
					Nuestro municipio tiene una deliciosa gastronomía que caracteriza a todos los culiacanenses como son el cabrito tatemado, la barbacoa, chilorio, chorizo y camarones en aguachile o ceviche entre otros ricos platillos que nos representan a nuestra hermosa ciudad.
				</p>
				<p>
					Algunas de los lugares mas visitados por los turistas y las personas son : Jardín Botánico Culiacán, Zoologico Culiacan, Parque Las Riberas, Iglesia La Lomita, Santuario y historia, Parque Constitución, Puente Negro, Museo de Arte de Sinaloa, Parque Ernesto Millán Escalante,  Modular Ines Arredondo, Centro INAH Sinaloa, Auditorio Parque Civico Culiacan.					
				</p>
				
			</div>
		</div>
		<div class="col-md-7" id="contenido-nosotros-slider">
			<div id="rev_slider_6_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;max-height:646px;">
                <div id="rev_slider_6_1" class="rev_slider fullwidthabanner" style="display:none;max-height:646px;height:646px;">
                    <ul>
                        <li  data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan.jpg" alt="bg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan2.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan3.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan4.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan5.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan6.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan7.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan8.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan9.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/culiacan/culiacan10.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                    </ul>
                    <div class="tp-bannertimer"></div>
                </div>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="texto">
				<h2>Vegetación</h2>
					<p>
						Los tipos de vegetación proporcionan condiciones únicas desde el punto de vista de la vegetación que existe en esta región del planeta, por otro lado en la superficie del municipio de Culiacán existe gran diversidad de plantas como: coco de aceite, yute, huizache, palo blanco, guamuchil, tule, etc. También se encuentran sus terrenos cercanos a la costa existen numerosas lagunas y esteros de aguas salobres, por lo que ahí se establece el manglar, y su actividad agrícola agrícola ocupa un porcentaje de la superficie.
					</p>
					<h2>Fauna</h2>
					<p>
						En cuanto a la fauna las especies de animales que habitan en Culiacán son el jabalí, venado cola blanca, ratón, zorrillo, codorniz, ocelote, boas, murciélago, etc. mientras que en el manglar habitan cocodrilos, caimanes, iguanas y en ambientes acuáticos ballena gris, delfín, camarón, tortugas, mero, pargo, robalo y corvina.
					</p>
					<h2>Zonas Verdes</h2>
				   	<p>	
				   		 En Culiacán las áreas verdes, estás en dos parques, en el Jardín Botánico que se encuentra ubicado al este de la ciudad, esta zona de la ciudad comprende 10 hectáreas donde podemos admirar una gran variedad de plantas de los diferentes ecosistemas y el Zoológico de Culiacán que cuenta con variedad de plantas y animales de diferentes especies, además es un centro recreativo que cuenta con canchas para realizar deportes y un área de juegos.
				   	</p>
			   </div>
		</div>
	</div>
</div>
<div class="row" id="contenido_sucursal_direccion">
		<h2>Sucursal Culiacan</h2>
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="col-md-6">
				<i class="soap-icon-address"></i>
				<h3>Dirección</h3>
				<p>Alfonso G. Calderón Velarde S/N Local #15 Desarrollo urbano Tres ríos, Culiacán, Sinaloa C.P. 80020</p>
			</div>
			<div class="col-md-6">
				<i class="soap-icon-phone"></i>
				<h3>Teléfono</h3>
				<p> 01 (667) 761 29 00</p>
			</div>
		</div>
	</div>
	<div class="mapa-extendido">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d28969.88145807191!2d-107.4203706534949!3d24.82162963181863!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86bcda0c2131f4cf%3A0x3df1969961312d05!2sDesarrollo+Urbano+Tres+R%C3%ADos%2C+80020+Culiac%C3%A1n+Rosales%2C+Sin.!5e0!3m2!1ses-419!2smx!4v1518888866980" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>
