<!DOCTYPE html>
<html lang="es" >
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <head>
        <title>AUS - Acerca de nosotros</title>
        <?php require_once("view/includes/script_header.phtml"); ?>
    </head>
    <body class="home page page-id-785 page-template page-template-templates page-template-template-home page-template-templatestemplate-home-php wpb-js-composer js-comp-ver-4.9.1 vc_responsive">
        <div id="page-wrapper">
            <?php require_once("view/includes/header.phtml"); ?>
            <?php require_once("view/sucursales/culiacan/contenido-culiacan.phtml"); ?>
            <?php require_once("view/includes/footer.phtml"); ?>
        </div>
        
        <?php require_once("view/includes/script_footer.phtml"); ?>
    </body>
</html>
