<div class="search-box-wrapper">
	<div class="search-box container">
		<div class="search-tab-content">
			<div id="tipo-servicios" class="">
				<div class="seleccion-servicio">
					<h2>Selección de tipo de servicio</h2>
				</div>
				<form role="search" action="">
					<div class="row">
						<div class="form-group col-sm-12 col-md-12 ">
							<h4 class="title">Tipo de servicio</h4>
							<label class="radio-inline"><input type="radio">Expreso</label>

							<label class="radio-inline"><input type="radio">Ordinario</label>
						</div>
						<div class="form-group col-sm-6 col-md-2 ">
			                <label class="hidden-xs">&nbsp;</label>
			                <button type="button" class="full-width icon-check animated inicio-datos" data-animation-type="bounce" data-animation-duration="1">Continuar</button>
			            </div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
