<div class="search-box-wrapper">
	<div class="search-box container">
		<div class="search-tab-content">
			<div id="tipo-datopersonal" class="">
				<div class="title-form">
					<h2>Selección de datos personales</h2>
				</div>
				<form role="search" action="">
					<div class="row">
						<div class="form-group col-sm-3 col-md-3 ">
							<h4 class="title">Mi llave(Opcional)</h4>
							<input type="text" name="datos-personales" class="input-text full-width" placeholder="Mi llave">
						</div>
						<div class="form-group col-sm-3 col-md-3 ">
							<h4 class="title">Nombre</h4>
							<input type="text" name="nombre-personal" class="input-text full-width" placeholder="Nombre">
						</div>
						<div class="form-group col-sm-3 col-md-3 ">
							<h4 class="title">Apellido</h4>
							<input type="text" name="apellido-personal" class="input-text full-width" placeholder="Apellido">
						</div>
						<div class="form-group col-sm-3 col-md-3 ">
							<h4 class="title">Sexo</h4>
							<label class="radio-inline"><input type="radio">Hombre</label>
							<label class="radio-inline"><input type="radio">Mujer</label>
						</div>
						<div class="form-group col-sm-6 col-md-2 fixheight">
			                <label class="hidden-xs">&nbsp;</label>
			                <button type="button" class="full-width icon-check animated inicio-datos" data-animation-type="bounce" data-animation-duration="1">Guardar</button>
			            </div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>