<!-- <div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="destinos-inicio">
    <div class="container">
        <div class="row ">
            <div class="title col-md-12  ">
              <h1>Cónoce nuestros destinos</h1>
            </div>
            <div class="col-md-6 img-destinos" >
              <a href="#modalCuliacan" data-toggle="modal" data-target="#modalCuliacan" title="Amazing Places">
                <div class="img-des">
                    <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/culiacan.jpg" class="attachment-widget-thumb wp-post-image" alt="1" />
                    <div class="titulo-des">
                      <h2>
                        Culiacán
                      </h2>
                    </div>
                </div> 
              </a>
            </div>
            <div class="col-md-6 img-destinos" >
              <a href="" title="Travel Insurance">
                <div class="img-des">
                  <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/mazatlan.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                  <div class="titulo-des">
                      <h2>
                        Mazatlán
                      </h2>
                    </div>
                </div>
              </a>
            </div>
            <div class="clearfix">
            </div>
            <div class="col-md-6 img-destinos" >
              <a href="" title="Travel Insurance">
                <div class="img-des">
                  <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/el_rosario.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                  <div class="titulo-des">
                        <h2>
                          El rosario
                        </h2>
                  </div>
                </div>
              </a>
            </div>
            <div class="col-md-6 img-destinos" >
              <a href="" title="Travel Insurance">
                <div class="img-des">
                    <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/escuinapa.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                    <div class="titulo-des">
                      <h2>
                        Escuinapa
                      </h2>
                    </div>
                </div>
              </a>
            </div>
        </div>
    </div>
</div> -->




<div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="destinos-inicio">
    <div class="container tab-container clearfix">
        <div class="row ">
          <div class="title col-md-12  ">
            <h1>Cónoce nuestros destinos</h1>
          </div>
          <div class="col-md-6 tabs clearfix">
            <div class="row">
              <div class="col-md-6 img-destinos" >
                <a href="#modalCuliacan" data-toggle="tab">
                  <div class="img-des">
                      <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/culiacan.jpg" class="attachment-widget-thumb wp-post-image" alt="1" />
                      <div class="titulo-des">
                        <h2>
                          Culiacán
                        </h2>
                        
                      </div>
                  </div> 
                </a>
              </div>
              <div class="col-md-6 img-destinos" >
                <a href="#modalMazatlan" data-toggle="tab">
                  <div class="img-des">
                    <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/mazatlan.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                    <div class="titulo-des">
                        <h2>
                          Mazatlán
                        </h2>
                      </div>
                  </div>
                </a>
              </div>
              <div class="col-md-6 img-destinos" >
                <a href="#modalElrosario" data-toggle="tab">
                  <div class="img-des">
                    <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/el_rosario.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                    <div class="titulo-des">
                          <h2>
                            El rosario
                          </h2>
                    </div>
                  </div>
                </a>
              </div>
              <div class="col-md-6 img-destinos" >
                <a href="#modalEscuinapa" data-toggle="tab">
                  <div class="img-des">
                      <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/escuinapa.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                      <div class="titulo-des">
                        <h2>
                          Escuinapa
                        </h2>
                      </div>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-6 tab-content">
            <div id="modalCuliacan" class="tab-pane fade active in">
              <div>
                  <h4>
                    Culiacán</h4>
                  <div class="parte1">
                        <p>
                          Culiacán oficialmente es conocido como Culiacán Rosales, es una ciudad que se encuentra ubicada al noroeste de México, capital y ciudad mas grande del estado de Sinaloa tiene una población de 755 510 habitantes (2010).
                           Culiacán es una de las ciudades mas visitadas de Sinaloa por sus bellos alrededores, sus lugares históricos, por sus fiestas populares, sus artesanías y por sus costumbres y tradiciones.
                        </p>
                        <p>
                          Algunas de los lugares mas visitados por los turistas y las personas son :
                          <ul>
                            <li>Jardín Botánico Culiacán.</li>
                            <li>Zoológico Culiacán.</li>
                            <li>Parque Las Riberas.</li>
                            <li>Iglesia La Lomita.</li>
                            <li>Santuario y historia.</li>
                            <li>Parque Constitución.</li>
                            <li>Puente Negro.</li>
                            <li>Museo de Arte de Sinaloa.</li>
                            <li>Parque Ernesto Millán Escalante.</li>
                            <li>Modular Ines Arredondo.</li>
                            <li>Centro INAH Sinaloa.</li>
                            <li>Auditorio Parque Cívico Culiacán.</li>
                          </ul>
                        </p>
                        
                  </div>
                        <div class="parte2" style="display:none;">}
                          <p>
                          Nuestro municipio tiene una deliciosa gastronomía que caracteriza a todos los culiacanenses como son el cabrito tatemado, la barbacoa, chilorio, chorizo y camarones en aguachile o ceviche entre otros ricos platillos que nos representan a nuestra hermosa ciudad.
                        </p>
                          <p>
                          Los tipos de vegetación proporcionan condiciones únicas desde el punto de vista de la vegetación que existe en esta región del planeta, por otro lado en la superficie del municipio de Culiacán existe gran diversidad de plantas como: coco de aceite, yute, huizache, palo blanco, guamuchil, tule, etc. También se encuentran sus terrenos cercanos a la costa existen numerosas lagunas y esteros de aguas salobres, por lo que ahí se establece el manglar, y su actividad agrícola agrícola ocupa un porcentaje de la superficie.
                        </p>
 
                        <p>
                          En cuanto a la fauna las especies de animales que habitan en Culiacán son el jabalí, venado cola blanca, ratón, zorrillo, codorniz, ocelote, boas, murciélago, etc. mientras que en el manglar habitan cocodrilos, caimanes, iguanas y en ambientes acuáticos ballena gris, delfín, camarón, tortugas, mero, pargo, robalo y corvina.
                        </p>
                        <h3>Zonas verdes</h3>
                        <p> En Culiacán las áreas verdes, estás en dos parques, en el Jardín Botánico que se encuentra ubicado al este de la ciudad, esta zona de la ciudad comprende 10 hectáreas donde podemos admirar una gran variedad de plantas de los diferentes ecosistemas y el Zoológico de Culiacán que cuenta con variedad de plantas y animales de diferentes especies, además es un centro recreativo que cuenta con canchas para realizar deportes y un área de juegos.</p>
                        </div>
              </div> 
                        <button id="vermas">Ver más</button>
            </div>
            <div id="modalMazatlan" class="tab-pane fade">
              <div>
                  <h4>Mazatlán</h4>
                  <div class="parte1">
                    <p>Reconocido por sus 20 kilómetros de cálidas playas, exquisita gastronomía de fama internacional, 7 kilómetros de espectacular Malecón con impresionantes puestas de sol, el faro natural más alto del mundo, el Carnaval con mayor tradición de México, cuna de la tradicional música de banda y el Centro Histórico más importante del noroeste de México, Mazatlán se considera un destino familiar de playa por excelencia con una hospitalidad y calidez tradicional para recibir al turista.</p>

                    <p>La "Perla del Pacífico" rodeada de lugares históricos, riquísima gastronomía y extraordinarias playas.</p>
                    <p>Disfrute y viva la cultura y tradiciones de esta ciudad que se fundó en los años 1500's, y que aún mantiene muchos de sus edificios históricos en su estilo arquitectónico original.</p>
 
                    <p>Música, danza, teatro, ópera y muchas otras actividades culturales son parte del diario acontencer de la vida en Mazatlán, donde hay dos temporadas culturales muy importantes: el Festival Cultural Mazatlán, de octubre a diciembre, y el Festival de Primavera, de febrero a junio. El histórico teatro Ángela Peralta es el ícono de la cultura de Mazatlán.</p>

                   
                  </div>
                  <div class="parte2"  style="display:none;">
                     <p>Da un paseo por el Centro Histórico. Ahí encontrarás la Plaza Machado, la Catedral y el teatro Ángela Peralta, el cual tiene el título de Patrimonio Histórico Nacional , Saborea su deliciosa gastronomía: aguachile, pescado zarandeado, tacos gobernador, tacos de marlin, callos de hacha, ceviche de serra y más. *RESTAURANTES: El Muchacho Alegre, El Torito, Pancho´s y La Costa Marinera O  Camina por el malecón, el segundo más largo del mundo. A lo largo de su recorrido, pasarás por restaurantes, bares, hoteles, monumentos y mucho más.</p>
                     <p>NOTA: El transporte tradicional de Mazatlán es la Pulmonía , un vehículo "típico" para pasear por la zona dorada o el malecón. Puedes . Visitar el Acuario de Mazatlán, considerado como un de los más bonitos de México. Existe un espacio llamado la  "pecera oceánica" la cual es la mas grande de Latinoamérica. </p>

                     <p>Pasa una tarde en las mejores playas: Olas Altas, Playa Norte, Playa Gaviotas, Isla La Piedra, Playa Cerritos y más. Además, es típico escuchar música de banda o banda en vivo en algunas de las playas. Nota: Para Isla de la Piedra, es necesario tomar un pequeño barquito. </p>

                     <p>Sube al Faro de Mazatlán, considerado el segundo faro natural más alto del mundo. Se encuentra ubicado en la cima del Cerro del Crestón, donde disfrutarás las mejores vistas panorámicas de Mazatlán.</p>

                    <p>Conoce las tres islas (Isla Venados, Isla Pájaros e Isla Lobos). Las playas son tranquilas y puedes practicar snorkel, kayak y buceo. Estas tres islas promueven la conservación ecológica y son consideradas como centro ecológico. </p>

                    <p>Disfruta la vida nocturna, conoce la disco Valentino's, la más famosa de Mazatlán y realiza un recorrido por la gran variedad de bares y antros que existen en la zona del Malecón.</p>
                     
                     <p>Asiste al Carnaval de Mazatlán, es el tercero más importante del mundo después del de Río de Janeiro y Nueva Orleáns. Se realiza cada año a mediados de febrero.</p>
                  </div>
              </div> 
              <button id="vermas">Ver más</button>
            </div>
            <div id="modalElrosario" class="tab-pane fade">
              <div>
                  <h4>El rosario</h4>
                  <div class="parte1">
                    <p>El nombre de esta población del estado de Sinaloa, corresponde tanto a su población más importante, como también para el municipio entero. Se localiza en la región sur del territorio sinaloense. Limita al norte con los municipios de Mazatlán y de Concordia; por el sur colinda con Escuinapa y el estado de Nayarit; al oriente con el territorio duranguense, y al poniente con las aguas del Océano Pacífico.</p>
                    <p>La fundación de la ciudad tuvo lugar el día 3 de agosto de 1655. Este evento está rodeado de una interesante anécdota. En tal fecha un caporal, Bonifacio Rojas, se dio cuenta de que le faltaba una res y fue a buscarla. Avanzó por el río hasta llegar a la Loma de Santiago. Allí encontró a la res que se le había escapado. Como se había hecho de noche, Rojas decidió encender una fogata. Al día siguiente, tras despertarse, se llevó una gran sorpresa: mientras removía los restos de la fogata, descubrió una enorme cantidad de plata fundida, pegada a una peña. Antes de dar apresurado aviso de su hallazgo a su patrón, el caporal resolvió dejar un rosario para identificar el sitio que había encontrado.</p>
                    <p>El patrón, entusiasmado por lo que había descubierto su caporal, corrió donde estaba el rosario para comprobarlo y al ver la plata, realizó un tajo en la peña y comenzó la explotación de este metal precioso. Eso derivó en el nacimiento de la ciudad del Rosario.</p>
                    
                  </div>
                  <div class="parte2"  style="display:none;">
                    <h3>¿Qué visitar en El Rosario Pueblo Magico?</h3>
                    <p>Actualmente El Rosario es un Pueblo Mágico que ha sabido mantenerse vivo. Se encuentra a unos 70 kilómetros del puerto de Mazatlán. De entre las figuras más relevantes de El Rosario hay que mencionar a la cantante vernácula Lola Beltrán, quien tuvo un enorme  cariño por esta comunidad de Sinaloa. Algunas importantes comunidades de la región son las de Pozole, Chameta, Agua Verde, Los Ojitos y Niebla. Son sitios de gran interés turístico, para conocer la actividad ganadera, pesquera y agrícola que definen a esta zona del país.</p>
                    <p>Estamos en un territorio donde se percibe en gran medida la influencia de los antiguos totorames, indígenas que habitaron en la zona donde colinda Sinaloa con el estado de Durango. Se trata de un destino turístico que cuenta con un clima muy grato y un rico ecosistema.</p>
                    <p>De entre los tesoros turísticos del Pueblo Mágico de El Rosario se deben mencionar los siguientes: la Iglesia de Nuestra Señora de El Rosario, la Casa de Lola Beltrán y el Museo de la Cultura Totorame, en Chametla.</p>
                    <p>También son imperdibles las playas de El Caimanero, la bella laguna de Iguanero, el centro histórico de El Rosario, las minas del Tajo y el Malecón del Río Baluarte.</p>
                    <h3>Información relevante acerca de El Rosario Pueblo Magico</h3>
                    <p>A lo largo de los siglos XVIII y XIX El Rosario fue un significativo centro minero. En 1700 este Pueblo Mágico fue sede de los poderes del área de California, Baja California y Sonora. Durante un buen tiempo fue una especie de ciudad- asilo y a esta población se le debe en mucho, la importancia que Mazatlán alcanzó como puerto. Por aquellos años San Blas, en el estado de Nayarit, era el puerto más relevante de la región, puesto que por allí se enviaba la mayor parte del Mineral que se obtenía de El Rosario. Por tal motivo, en 1800, se incrementó el apoyo para que Mazatlán también ayudara como puerto de salida de las embarcaciones cargadas de plata y oro.</p>
                    <h3>Actividades a realizar en El Rosario Pueblo Mágico</h3>
                    <p>La celebración típica más importante de El Rosario es la que se realiza para festejar a la Virgen del Rosario. Esta última tiene lugar el primer domingo de octubre. También es interesante y de gran convocatoria, la Feria de la Primavera, uno de los eventos en su tipo con mayor antigüedad en México, la cual tiene lugar del 1 al 10 de mayo. 
                    Además, como parte de un viaje a El Rosario, conviene conocer las pintorescas comunidades indígenas de Matatán y Cacalotán, en las cuales también se realizan notables celebraciones populares.</p>
                  </div>
              </div>
              <button id="vermas">Ver más</button> 
            </div>
            <div id="modalEscuinapa" class="tab-pane fade">
              <div>
                  <h4>Escuinapa</h4>
                  <div class="parte1">
                    <p>La localidad de Escuinapa está situado en el Municipio de Escuinapa (en el Estado de Sinaloa). Hay 30790 habitantes. Escuinapa está a 18 metros de altitud. 
                        En la localidad hay 15268 hombres y 15522 mujeres el 0,45% de la población es indígena, y el 0,16% de los habitantes habla una lengua indígena. El 0,00% de la población habla una lengua indígena y no habla español.</p>
                    <p>Se tiene conocimiento de que los primeros pobladores de esta región fueron descendientes de la raza azteca, quienes aprovecharon la sal de las marismas, la caza y la pesca y se establecieron fundando un poblado de nombre Ahuchén. </p>
                    <p>Los pobladores de Ahuchén abrumados por los mosquitos que trasmitían fiebre, la tierra salitrosa y el constante asedio de los piratas, se trasladaron a otro lugar al sur, y fundaron una comunidad que llamaron "Pueblo Viejo". Sin embargo, pronto se vieron en la necesidad de volver a emigrar por los constantes ataques de bandoleros. A poca distancia encontraron un lugar con mayor seguridad y formaron un nuevo pueblo que llamaron Izquinapa. </p>
                    
                  </div>
                  <div class="parte2"  style="display:none;">
                    <p> En 1602 había 20 vecinos en el poblado de Izquinapa hoy Escuinapa, pero no se registran sus nombres. </p>
                    <p> En 1912 se aprueba la Ley núm. 21 sobre la creación de municipalidades como forma interna del gobierno estatal, pero es hasta 1915 en que se suprimen las directorías políticas, cuando se erigen los primeros once municipios libres, siendo Escuinapa uno de ellos, creado por Decreto del 7 de septiembre de 1915 y ratificada su categoría en la Constitución de 1917.</p>
                    <p>El Puerto de Teacapan Ubicado al poniente del municipio, lugar que se distingue por la belleza natural que posee y las playas del litoral del pacífico; lo encontramos a 40 kilómetros de la cabecera municipal. Se caracteriza por su potencial turístico natural y su infraestructura y servicios de que dispone.</p>
                    <p>La cercanía del municipio de Escuinapa con este polo de desarrollo y los atractivos propios de la región, permiten su integración al circuito turístico Mazatlán-Escuinapa-Teacapán.</p>
                    <p> Como atractivo regional turístico se considera también la celebración del día del marino. </p>
                  </div>
              </div>
              <button id="vermas">Ver más</button> 
            </div>
          </div>
        </div>
    </div>
</div>

<script>
  jQuery(document).ready(function(){ 
       jQuery('.tab-pane #vermas').toggle(

        
           // Primer click
        function(e){ 
           jQuery('.parte2').slideDown();
           jQuery('html,body').animate({
                    scrollTop: jQuery(".parte2").offset().top
        }, 500);
           jQuery(this).text('Ver menos');
            e.preventDefault();
        }, // Separamos las dos funciones con una coma
      
        // Segundo click
        function(e){ 
           jQuery('.parte2').slideUp();
           jQuery('html,body').animate({
                    scrollTop: jQuery(".parte1").offset().top
        }, 500);
           jQuery(this).text('Ver más');
            e.preventDefault();
        }


        );
   });
</script>
<!-- 
<div class="tab-container clearfix ">
  <ul class="tabs clearfix">
    <li class="">
      <a href="#1459348045708-5" data-toggle="tab">Satisfied customers</a>
    </li>
    <li class="active">
      <a href="#1459348045772-3" data-toggle="tab">tours suggestions</a>
    </li>
    <li class="">
      <a href="#1459348045834-7" data-toggle="tab">Careers</a>
    </li>
  </ul>
  <div class="tab-content">
    <div id="1459348045708-5" class="tab-pane fade">
      <div>
          <p>
          <img class="pull-left" src="../../wp-content/uploads/2014/11/tabs01.png" alt="tab-image"></p>
          <h4>Ocean Park Tour</h4>
          <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Vivamus elementum, ligula vehicula enenatis semper, magna lorem aliquet lacus, in euismod sem lectus. ligula vehicula enenatis semper, magna lorem aliquet lacus euismod sem velit ve.</p>
          <p>Ligula vehicula enenatis semper, magna lorem aliquet lacusin ante dapibus dictum. fugats vitaes nemo minima rerums unsers sadips amets.</p>
      </div> 
    </div>
    <div id="1459348045772-3" class="tab-pane fade active in">
        <div>
            <p>
            <img class="pull-left" src="../../wp-content/uploads/2014/11/places02.jpg" alt="tab-image"></p>
            <h4>Ocean Park Tour</h4>
            <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Vivamus elementum, ligula vehicula enenatis semper, magna lorem aliquet lacus, in euismod sem lectus. ligula vehicula enenatis semper, magna lorem aliquet lacus euismod sem velit ve.</p>
            <p>Ligula vehicula enenatis semper, magna lorem aliquet lacusin ante dapibus dictum. fugats vitaes nemo minima rerums unsers sadips amets.</p>
        </div> 
    </div>
    <div id="1459348045834-7" class="tab-pane fade">
      <div>
        <p>
        <img class="pull-left" src="../../wp-content/uploads/2014/11/tabs01.png" alt="tab-image"></p>
        <h4>Ocean Park Tour</h4>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Vivamus elementum, ligula vehicula enenatis semper, magna lorem aliquet lacus, in euismod sem lectus. ligula vehicula enenatis semper, magna lorem aliquet lacus euismod sem velit ve.</p>
        <p>Ligula vehicula enenatis semper, magna lorem aliquet lacusin ante dapibus dictum. fugats vitaes nemo minima rerums unsers sadips amets.</p>
      </div> 
    </div>
  </div>
</div> -->