<!-- Modal Culiacan -->
<div class="modal fade modal-ubicaciones" id="modalCuliacan" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Sucursal Culiacán</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 img-modal-sucursal">
                        <img src="<?= Conectar::ruta_web()?>script/images/img/777.jpg" alt="">
                    </div>
                    <div class="col-md-6 texto-modal-sucursal">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- fin Modal Culiacan -->
<!-- Modal La cruz -->
<div class="modal fade modal-ubicaciones" id="modalLacruz" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Sucursal La cruz</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 img-modal-sucursal">
                        <img src="<?= Conectar::ruta_web()?>script/images/img/777.jpg" alt="">
                    </div>
                    <div class="col-md-6 texto-modal-sucursal">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- fin Modal La cruz -->
<!-- Modal mazatlan -->
<div class="modal fade modal-ubicaciones" id="modalMazatlan" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Sucursal Mazatlán</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 img-modal-sucursal">
                        <img src="<?= Conectar::ruta_web()?>script/images/img/777.jpg" alt="">
                    </div>
                    <div class="col-md-6 texto-modal-sucursal">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- fin Modal mazatlan -->
<!-- Modal El rosario -->
<div class="modal fade modal-ubicaciones" id="modalElrosario" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Sucursal El rosario</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 img-modal-sucursal">
                        <img src="<?= Conectar::ruta_web()?>script/images/img/777.jpg" alt="">
                    </div>
                    <div class="col-md-6 texto-modal-sucursal">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- fin Modal El rosario -->
<!-- Modal Esquinapa -->
<div class="modal fade modal-ubicaciones" id="modalEsquinapa" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Sucursal Esquinapa</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 img-modal-sucursal">
                        <img src="<?= Conectar::ruta_web()?>script/images/img/777.jpg" alt="">
                    </div>
                    <div class="col-md-6 texto-modal-sucursal">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- fin Modal Esquinapa -->
<!-- Modal Guasave -->
<div class="modal fade modal-ubicaciones" id="modalGuasave" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Sucursal Guasave</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 img-modal-sucursal">
                        <img src="<?= Conectar::ruta_web()?>script/images/img/777.jpg" alt="">
                    </div>
                    <div class="col-md-6 texto-modal-sucursal">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- fin Modal guasave -->