<div class="parallax section global-map-area" data-stellar-background-ratio="0.5">
                            <div class="image-box style7">
                                <div class="vc_row wpb_row vc_inner vc_row-fluid inner-container">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-sms-6 wpb_column col-sm-6 col-md-3">
                                                <div class="vc_column-inner ">
                                                    <div class="wpb_wrapper">
                                                        <article class="box">
                                                            <figure class="middle-block">
                                                                <a href="#" title=""><img src="<?= Conectar::ruta_web()?>script/images/extra/14.jpg" alt="imageframe-image" width="283" height="200" class="middle-item" /><span class="opacity-wrapper"></span></a>
                                                            </figure>
                                                            <div class="details">
                                                                <h4><a href="#">Best Price Guarantee</a></h4>
                                                                <p>Nunc cursus libero purus ac congue arcu cursus ut sed vitae pulvinar massa idporta nequetiam elerisque mi id faucibus iaculis vitae pulvinar.
                                                                    <br />
                                                            </div>
                                                        </article>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sms-6 wpb_column col-sm-6 col-md-3">
                                                <div class="vc_column-inner ">
                                                    <div class="wpb_wrapper">
                                                        <article class="box">
                                                            <figure class="middle-block">
                                                                <a href="#" title=""><img src="<?= Conectar::ruta_web()?>script/images/extra/21.jpg" alt="imageframe-image" width="283" height="200" class="middle-item" /><span class="opacity-wrapper"></span></a>
                                                            </figure>
                                                            <div class="details">
                                                                <h4><a href="#">Travel Insurance</a></h4>
                                                                <p>Nunc cursus libero purus ac congue arcu cursus ut sed vitae pulvinar massa idporta nequetiam elerisque mi id faucibus iaculis vitae pulvinar.
                                                                    <br />
                                                            </div>
                                                        </article>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sms-6 wpb_column col-sm-6 col-md-3">
                                                <div class="vc_column-inner ">
                                                    <div class="wpb_wrapper">
                                                        <article class="box">
                                                            <figure class="middle-block">
                                                                <a href="#" title=""><img src="<?= Conectar::ruta_web()?>script/images/extra/31.jpg" alt="imageframe-image" width="283" height="200" class="middle-item" /><span class="opacity-wrapper"></span></a>
                                                            </figure>
                                                            <div class="details">
                                                                <h4><a href="#">Why Choose Us</a></h4>
                                                                <p>Nunc cursus libero purus ac congue arcu cursus ut sed vitae pulvinar massa idporta nequetiam elerisque mi id faucibus iaculis vitae pulvinar.
                                                                    <br />
                                                            </div>
                                                        </article>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-sms-6 wpb_column col-sm-6 col-md-3">
                                                <div class="vc_column-inner ">
                                                    <div class="wpb_wrapper">
                                                        <article class="box">
                                                            <figure class="middle-block">
                                                                <a href="#" title=""><img src="<?= Conectar::ruta_web()?>script/images/extra/41.jpg" alt="imageframe-image" width="283" height="200" class="middle-item" /><span class="opacity-wrapper"></span></a>
                                                            </figure>
                                                            <div class="details">
                                                                <h4><a href="#">Need Help?</a></h4>
                                                                <p>Nunc cursus libero purus ac congue arcu cursus ut sed vitae pulvinar massa idporta nequetiam elerisque mi id faucibus iaculis vitae pulvinar.
                                                                    <br />
                                                            </div>
                                                        </article>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>