<?php 
    /*
       <div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="servicios-extra">
            <div class="container-fluid">
                <div class="row ">
                    <div class="col-md-6 animated" data-animation-type="fadeInUp" data-animation-duration="1" data-animation-delay="">
                        <div class="imagen col-md-5">
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/sorprendida.png" alt=""> 
                        </div>
                        <div class="texto col-md-7">
                            <h3>Tenemos el mejor servicio de transporte de pasajeros. Nuestro equipo de trabajo está totalmente capacitado para brindarle la mejor atención.</h3>
                            <h2>Compruébalo !</h2>
                        </div>
                    </div>
                    <div class="col-md-6 img-extra animated" data-animation-type="fadeInUp" data-animation-duration="1" data-animation-delay="">
                        <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/AUSEQUPO.jpg" alt="">
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-6 img-extra animated" data-animation-type="fadeInUp" data-animation-duration="1" data-animation-delay="">
                        <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/AUSWIFI1.jpg" alt="">
                    </div>
                    <div class="col-md-6 animated" id="texto2" data-animation-type="fadeInUp" data-animation-duration="1" data-animation-delay="">
                       
                    </div>
                </div>
            </div>
        </div> 
    */

 ?>
<div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="aus-card">
    <div class="container-fluid">
        <div class="row ">
           <div class="col-md-6 col-md-offset-3">
            <div class="texto">
                <h2>Afiliate a nuestro programa de lealtad y obtén increíbles beneficios.</h2>
            </div>
            <div class="button-afiliarse">
                <a href="<?= Conectar::ruta_web() ?>afiliarse/" title="" class="btn " id="btn-afiliarse">Afiliese aquí <i class="fa fa-arrow-right" aria-hidden="true"></i> </a>
            </div>
               <img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/aus-card-banner3.png" alt="">
            
           </div>
        </div>
    </div>
</div>