<div class="parallax global-map-area" id="mapa-sucursales" data-stellar-background-ratio="0.5">
    <div class="promo-box honeymoon">
        <div class="container">
            <div class="col-md-12 animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="">
                <div class="row">
                    <div class="col-md-12 title-map">
                        <h1 class="title">Encuentra la sucursal más cercana</h1>
                    </div>
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/">
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                Culiacán
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/" >
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                La cruz
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/" >
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2">
                            <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                Mazatlán
                            </div>
                        </a>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-4 col-md-offset-2 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/" >
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                El rosario
                            </div>
                        </a>
                    </div>
                    
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/">
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                Esquinapa
                            </div>
                        </a>
                    </div>
                    
                </div>
            </div>


            <?php 
                /*

                    <div class="content-section description pull-right col-sm-6">
                        <div class="table-wrapper hidden-table-sm">
                            <div class="table-cell">
                                <div>
                                    <h1 class="title">Encuentra la sucursal más cercana</h1>
                                    <p>Ofrecemos calidad en el servicio de autobuses de pasajeros en el estado de Sinaloa, desde Culiacán, La Cruz, Mazatlán, El Rosario, Esquinapa, Guasave y Los Mochis.</p>
                                </div>
                                <div class="image-box style9">
                                    <div class="vc_row wpb_row vc_inner row places">
                                        <div class="col-sms-4 wpb_column col-sm-4">
                                            <div class="vc_column-inner ">
                                                <div class="wpb_wrapper">
                                                    <article class="box">
                                                        <div class="animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="0">
                                                            <figure class="middle-block">
                                                                <a href="" title="" class="hover-effect yellow"><img src="<?= Conectar::ruta_web()?>script/images/extra/places01.jpg" alt="paris" width="306" height="170" class="middle-item" /></a>
                                                            </figure>
                                                        </div>
                                                        <div class="details">
                                                            <h4 class="box-title">Paris<small>(990+ PLACES)</small></h4>
                                                            <p><a class="button" title="" href="index3134.html?post_type=accommodation&amp;s=paris">SEE ALL</a></div>
                                                    </article>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sms-4 wpb_column col-sm-4">
                                            <div class="vc_column-inner ">
                                                <div class="wpb_wrapper">
                                                    <article class="box">
                                                        <div class="animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="0.4">
                                                            <figure class="middle-block">
                                                                <a href="index4550.html?post_type=accommodation&amp;s=greece" title="" class="hover-effect yellow"><img src="<?= Conectar::ruta_web()?>script/images/extra/places02.jpg" alt="greece" width="175" height="175" class="middle-item" /></a>
                                                            </figure>
                                                        </div>
                                                        <div class="details">
                                                            <h4 class="box-title">Greece<small>(990+ PLACES)</small></h4>
                                                            <p><a class="button" title="" href="index4550.html?post_type=accommodation&amp;s=greece">SEE ALL</a></div>
                                                    </article>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-sms-4 wpb_column col-sm-4">
                                            <div class="vc_column-inner ">
                                                <div class="wpb_wrapper">
                                                    <article class="box">
                                                        <div class="animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="0.8">
                                                            <figure class="middle-block">
                                                                <a href="indexafba.html?post_type=accommodation&amp;s=australia" title="" class="hover-effect yellow"><img src="<?= Conectar::ruta_web()?>script/images/extra/places03.jpg" alt="australia" width="340" height="226" class="middle-item" /></a>
                                                            </figure>
                                                        </div>
                                                        <div class="details">
                                                            <h4 class="box-title">Australia<small>(990+ PLACES)</small></h4>
                                                            <p><a class="button" title="" href="indexafba.html?post_type=accommodation&amp;s=australia">SEE ALL</a></div>
                                                    </article>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="image-container col-sm-6 "><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/Sinaloa.png" alt="couple" width="524" height="541" class="animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="" /></div>
                */ 
            ?>
        </div>
    </div>
</div>