<div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="inicio-contacto">
    <div class="container">
        <div class="vc_row wpb_row vc_inner row animated" data-animation-type="fadeInUp" data-animation-duration="1" data-animation-delay="">
            <div class="wpb_column col-sm-4 col-md-6">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <div class="contact-us-box">
                            <div>
                                <h1 class="title">
                                    ¿Dudas? </br>
                                    Nos interesa saber tu opinión <br/>
                                    Envíanos un mensaje
                                </h1>
                            </div>
                           
                        </div>
                    </div>
                </div>
            </div>
            <div class="wpb_column col-sm-8 col-md-6">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <div class="travelo-box" id="formulario-inicio-contacto" >
                            <div role="form" class="wpcf7" >
                                <div class="screen-reader-response"></div>
                                <form action="http://www.soaptheme.net/wordpress/travelo/standard-pages/contact-us/#wpcf7-f676-p671-o1" method="post" class="wpcf7-form" novalidate="novalidate">
                                    <div style="display: none;">
                                        <input type="hidden" name="_wpcf7" value="676">
                                        <input type="hidden" name="_wpcf7_version" value="4.2.2">
                                        <input type="hidden" name="_wpcf7_locale" value="en_US">
                                        <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f676-p671-o1">
                                        <input type="hidden" name="_wpnonce" value="0835ddb63b">
                                    </div>
                                    
                                    <div class="row form-group">
                                        <div class="col-xs-6">
                                            <label>Nombre</label><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required full-width" aria-required="true" aria-invalid="false"></span>
                                        </div>
                                        <div class="col-xs-6">
                                            <label>Email</label><span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false"></span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Mensaje</label><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="6" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false" placeholder="Escribe tu mensaje..."></textarea></span>
                                    </div>
                                    <p>
                                        <input type="submit" value="ENVIAR" class="wpcf7-form-control wpcf7-submit btn-large full-width"><img class="ajax-loader" src="" alt="Sending ..." style="visibility: hidden;"></p>
                                    <div class="wpcf7-response-output wpcf7-display-none"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>