<div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="servicios-a-bordo">
    <div class="container">
        <div class="row">
            <div class="wpb_column col-sm-12 animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <h1 class="title">Servicios a bordo</h1>
                        <div class="row hotel image-box listing-style2">
                            <div class="col-md-12">
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                            <i class="flaticon-asiento-camion"></i> 
                                        </div>
                                        <div class="text-servicios">
                                            <h2>Asientos reclinables</h2> 
                                        </div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="">
                                    <div class="col-md-3 icon-servicios" class="link-servicios-a-bordo">
                                        <div class="icon">
                                        <i class="flaticon-pantalla"></i></div>
                                        <div class="text-servicios"><h2>Mega pantallas HD</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-musica"></i></div>
                                        <div class="text-servicios"><h2>Música</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-wifi"></i></div>
                                        <div class="text-servicios"><h2>Conexión wifi</h2></div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-12 ">
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-pelicula"></i></div>
                                        <div class="text-servicios"><h2>Películas</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-sanitarios"></i></div>
                                        <div class="text-servicios"><h2>Sanitarios</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-conexion"></i></div>
                                        <div class="text-servicios"><h2>Conexiones eléctricas</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-cafeteria"></i>
                                        </div>
                                        <div class="text-servicios"><h2>Luz de lectura</h2></div>
                                    </div>
                                </a>
                            </div>
                            <!-- <div class='col-sm-6 col-sms-6 col-md-3'>
                                <article class="box">
                                    <figure>
                                        <a href="#" data-post_id="45" class="hover-effect popup-gallery"><img width="500" height="300" src="<?= Conectar::ruta_web()?>script/images/extra/4-500x300.jpg" class="attachment-biggallery-thumb wp-post-image" alt="4" /></a>
                                    </figure>
                                    <div class="details">
                                        <a title="View all" href="accommodation/hilton-hotel-and-resorts/index.html" class="pull-right button uppercase">select</a>
                                        <h4 class="box-title"><a href="accommodation/hilton-hotel-and-resorts/index.html">Hilton Hotel</a></h4>
                                        <label class="price-wrapper">
                                            <span class="price-per-unit">$120.00</span>avg/night </label>
                                    </div>
                                </article>
                            </div> -->
                            <!-- <div class='col-sm-6 col-sms-6 col-md-3'>
                                <article class="box">
                                    <figure>
                                        <a href="#" data-post_id="1145" class="hover-effect popup-gallery"><img width="500" height="300" src="<?= Conectar::ruta_web()?>script/images/extra/5-500x300.jpg" class="attachment-biggallery-thumb wp-post-image" alt="5" /></a>
                                    </figure>
                                    <div class="details">
                                        <a title="View all" href="accommodation/hotel-alpina/index.html" class="pull-right button uppercase">select</a>
                                        <h4 class="box-title"><a href="accommodation/hotel-alpina/index.html">Hôtel Alpina</a></h4>
                                        <label class="price-wrapper">
                                            <span class="price-per-unit">$120.00</span>avg/night </label>
                                    </div>
                                </article>
                            </div>
                            <div class='col-sm-6 col-sms-6 col-md-3'>
                                <article class="box">
                                    <figure>
                                        <a href="#" data-post_id="189" class="hover-effect popup-gallery"><img width="500" height="300" src="<?= Conectar::ruta_web()?>script/images/extra/7-500x300.jpg" class="attachment-biggallery-thumb wp-post-image" alt="7" /></a>
                                    </figure>
                                    <div class="details">
                                        <a title="View all" href="accommodation/hotel-colombina/index.html" class="pull-right button uppercase">select</a>
                                        <h4 class="box-title"><a href="accommodation/hotel-colombina/index.html">Hotel Colombina</a></h4>
                                        <label class="price-wrapper">
                                            <span class="price-per-unit">$260.00</span>avg/night </label>
                                    </div>
                                </article>
                            </div>
                            <div class='col-sm-6 col-sms-6 col-md-3'>
                                <article class="box">
                                    <figure>
                                        <a href="#" data-post_id="209" class="hover-effect popup-gallery"><img width="500" height="300" src="<?= Conectar::ruta_web()?>script/images/extra/6-500x300.jpg" class="attachment-biggallery-thumb wp-post-image" alt="6" /></a>
                                    </figure>
                                    <div class="details">
                                        <a title="View all" href="accommodation/hilton-molino-stucky-venice/index.html" class="pull-right button uppercase">select</a>
                                        <h4 class="box-title"><a href="accommodation/hilton-molino-stucky-venice/index.html">Hilton Molino Stucky</a></h4>
                                        <label class="price-wrapper">
                                            <span class="price-per-unit">$617.00</span>avg/night </label>
                                    </div>
                                </article>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




