<div id="rev_slider_6_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;max-height:646px;">
                <!-- START REVOLUTION SLIDER 4.6.5 fullwidth mode -->
                <div id="rev_slider_6_1" class="rev_slider fullwidthabanner" style="display:none;max-height:646px;height:646px;">
                    <ul>
                        <li  data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="off">
                            <!-- MAIN IMAGE -->
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/autobus-img/redimensionadas/slider1.jpg" alt="bg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                            <!-- LAYERS -->
                            <!-- LAYER NR. 1 -->
                            <!-- <div class="tp-caption lfl str" data-x="576" data-y="106" data-speed="1500" data-start="500" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 5;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/autobus.png" alt="" data-ww="650" data-hh="auto">
                            </div> -->
                            <!-- LAYER NR. 2 -->
                            <?php 
                                /*<div class="tp-caption lfr stl" data-x="27" data-y="359" data-speed="1500" data-start="800" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 6;"><img src="<?= Conectar::ruta_web()?>script/images/revslider1/homepage/island.png" alt="" data-ww="267" data-hh="187">
                                </div>*/
                            ?>
                            <!-- LAYER NR. 3 -->
                            <?php 
                                /*
                                <div class="tp-caption lfb stt" data-x="266" data-y="479" data-speed="1500" data-start="1100" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 7;"><img src="<?= Conectar::ruta_web()?>script/images/revslider1/homepage/ballon.png" alt="" data-ww="25">
                                </div>
                                <!-- LAYER NR. 4 -->
                                <div class="tp-caption lfl stt" data-x="384" data-y="441" data-speed="1500" data-start="1400" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 8;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/maletas.png" alt="" data-ww="262" data-hh="auto">
                                </div>
                                */
                            ?>
                            <!-- LAYER NR. 5 -->
                                <div class="tp-caption large_bold_white_med_2 lfb str tp-resizeme" data-x="700" data-y="181" data-speed="1500" data-start="1700" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 9; max-width: auto; max-height: auto; white-space: nowrap;">
                                <p class="caption-big-title">Un <strong><i>viaje</i></strong> rápido y seguro!</p>
                            </div>
                            <!-- LAYER NR. 6 -->
                            <div class="tp-caption lft stl" data-x="710" data-y="230" data-speed="1500" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 10;"><i class="flaticon-reloj"></i>
                            </div>
                            <!-- LAYER NR. 7 -->
                            <div class="tp-caption sfl stl" data-x="710" data-y="273" data-speed="1500" data-start="2300" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6700" data-endspeed="1300" style="z-index: 11;"><i class="flaticon-operador"></i>
                            </div>
                            <!-- LAYER NR. 8 -->
                            <div class="tp-caption sfl stt" data-x="710" data-y="317" data-speed="1500" data-start="2600" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 12;"><i class="flaticon-paqueteria"></i>
                            </div>
                            <!-- LAYER NR. 9 -->
                            <div class="tp-caption sfl stl" data-x="710" data-y="354" data-speed="1500" data-start="2900" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 13;"><i class="flaticon-dinero"></i>
                            </div>
                            <!-- LAYER NR. 10 -->
                            <div class="tp-caption large_bold_white_med lft str tp-resizeme" data-x="780" data-y="230" data-speed="1500" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 14; max-width: auto; max-height: auto; white-space: nowrap;"><span class="caption-medium-title">Salidas<strong> a </strong>tiempo</span>
                            </div>
                            <!-- LAYER NR. 11 -->
                            <div class="tp-caption large_bold_white_med lft stl tp-resizeme" data-x="780" data-y="274" data-speed="1500" data-start="3500" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 15; max-width: auto; max-height: auto; white-space: nowrap;"><span class="caption-medium-title">Operadores <strong>totalmente</strong> capacitados</span>
                            </div>
                            <!-- LAYER NR. 12 -->
                            <div class="tp-caption large_bold_white_med lft stt tp-resizeme" data-x="780" data-y="318" data-speed="1500" data-start="3800" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 16; max-width: auto; max-height: auto; white-space: nowrap;"><span class="caption-medium-title">Paquetería y mensajería</span>
                            </div>
                            <!-- LAYER NR. 13 -->
                            <div class="tp-caption large_bold_white_med lft stl tp-resizeme" data-x="780" data-y="357" data-speed="1500" data-start="4100" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 17; max-width: auto; max-height: auto; white-space: nowrap;"><span class="caption-medium-title">Precios accesibles</span>
                            </div>
                            <!-- LAYER NR. 14 -->
                            <div class="tp-caption tp-fade fadeout tp-resizeme" data-x="710" data-y="410" data-speed="1500" data-start="4400" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6700" data-endspeed="1300" style="z-index: 18; max-width: auto; max-height: auto; white-space: nowrap;"><a class="link link-home-slider-blue" href="#">Comprar boleto</a>
                            </div>
                        </li>
                        <!-- SLIDE  -->
                        <li id="slider2" data-transition="zoomout" data-slotamount="7" data-masterspeed="1000" data-saveperformance="off">
                            <!-- MAIN IMAGE -->
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/autobus-img/redimensionadas/autobus-9.jpg" alt="bg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                                                        
                            <!-- LAYER NR. 2 -->
                            <div class="tp-caption tp-fade fadeout" data-x="50" data-hoffset="0" data-y="bottom" data-voffset="0" data-speed="300" data-start="800" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 6;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/persona-viajera.png" alt="">
                            </div>
                            <!-- LAYER NR. 3 -->
                            <div class="tp-caption lfl str" data-x="756" data-y="500" data-speed="1500" data-start="1100" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 7;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/shadow.png" alt="">
                            </div>
                            <!-- LAYER NR. 4 -->
                            <div class="tp-caption sfr stl" data-x="801" data-y="319" data-speed="1500" data-start="1400" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="6500" data-endspeed="1500" style="z-index: 8;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/maletas.png" alt="">
                            </div>                            
                            <!-- LAYER NR. 6 -->
                            <div class="tp-caption sfr stb" data-x="798" data-y="450" data-speed="1500" data-start="2000" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7000" data-endspeed="1000" style="z-index: 10;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/watch.png" alt="">
                            </div>
                            <!-- LAYER NR. 9 -->
                            <div class="tp-caption sft stt tp-resizeme" data-x="350" data-y="center" data-voffset="40" data-speed="600" data-start="3600" data-easing="easeOutQuad" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7400" data-endspeed="600" style="z-index: 13; max-width: auto; max-height: auto; white-space: nowrap;">
                                <p class="caption-small-title">Autotransportes Unidos de Sinaloa</p>
                                <p class="caption-medium-title">Ofrecemos calidad en nuestros servicios !</p>
                            </div>
                            <!-- LAYER NR. 10 -->
                            <div class="tp-caption largewhitebg_button1 lfl stl tp-resizeme" data-x="440" data-y="395" data-speed="1500" data-start="3200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7000" data-endspeed="1000" style="z-index: 14; max-width: auto; max-height: auto; white-space: nowrap;"><a href="#">Comprar ahora !</a>
                            </div>
                            <!-- LAYER NR. 11 -->
                            <div class="tp-caption largewhitebg_button1 lfr str tp-resizeme" data-x="600" data-y="395" data-speed="1500" data-start="3500" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7000" data-endspeed="1000" style="z-index: 15; max-width: auto; max-height: auto; white-space: nowrap;"><a href="#">Más información</a>
                            </div>
                        </li>
                        <!-- SLIDE  -->
                        
                        <!-- SLIDE  -->
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <!-- MAIN IMAGE -->
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/slider8.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                            <!-- LAYERS -->
                            <!-- LAYER NR. 1 -->
                            <div class="tp-caption lfr fadeout" data-x="500" data-hoffset="10" data-y="0" data-voffset="0" data-speed="400" data-start="1200" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 5;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/promociones/circulo-5.png" alt="">
                            </div>
                            <!-- LAYER NR. 2 -->
                            <div class="tp-caption sfb fadeout" data-x="500" data-hoffset="10" data-y="0" data-speed="400" data-start="1700" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 6;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/promociones/circulo-6.png" alt="">
                            </div>
                            <!-- LAYER NR. 4 -->
                            <div class="tp-caption sfb fadeout" data-x="675" data-hoffset="10" data-y="160" data-speed="300" data-start="2100" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 8;"><h2 class="promo-title">50%</h2>
                            </div>
                            <div class="tp-caption sfb fadeout" data-x="620" data-hoffset="10" data-y="350" data-speed="300" data-start="2100" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 8;"><h3 class="promo-text">En el segundo boleto</h2>
                            </div>
                            
                            <!-- LAYER NR. 14 -->
                            <div class="tp-caption customin fadeout" data-x="right" data-hoffset="60" data-y="bottom" data-voffset="0" data-customin="x:800;y:450;rotationX:0;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:846;transformOrigin:50% 50%;" data-speed="600" data-start="1600" data-easing="Power3.easeInOut" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7400" data-endspeed="600" style="z-index: 18;"><img src="<?= Conectar::ruta_web()?>script/img_autotransportes/fondo/sorprendida.png" alt="">
                            </div>
                            <!-- LAYER NR. 15 -->
                            <div class="tp-caption promo-contenedor large_bold_white_med lfr stl tp-resizeme" data-x="25" data-y="181" data-speed="1500" data-start="1000" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7700" data-endspeed="300" style="z-index: 19; max-width: auto; max-height: auto; white-space: nowrap;">
                                <p class="caption-big-title">Tenemos <strong><i>excelentes promociones</i></strong> </br>para ti !</p>
                            </div>
                            <!-- LAYER NR. 24 -->
                           <!--  <div class="tp-caption tp-fade fadeout tp-resizeme" id="ver-mas-btn" data-x="129" data-y="410" data-speed="1500" data-start="1200" data-easing="Power3.easeInOut" data-splitin="none" data-splitout="none" data-elementdelay="0.1" data-endelementdelay="0.1" data-end="7000" data-endspeed="1000" style="z-index: 28; max-width: auto; max-height: auto; white-space: nowrap;"><a class="link link-home-slider-blue" href="#">Ver más</a>
                            </div> -->
                        </li>
                    </ul>
                    <div class="tp-bannertimer"></div>
                </div>
            </div>