<div class="header-fondo-culiacan mazatlan">
	<div class="">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Sucursal Mazatlan</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Sucursales - Mazatlan</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="mod_sucursal_culiacan">
	<div class="container" id="contenido-general-nosotros">
	<h1>MAZATLAN</h1>
	<div class="row">
		<div class="col-md-5" id="contenido-nosotros-texto">
			<div class="texto">
				<p>La "Perla del Pacífico" rodeada de lugares históricos, riquísima gastronomía y extraordinarias playas. 
					Reconocido por sus 20 kilómetros de cálidas playas, exquisita gastronomía de fama internacional, 7 kilómetros de espectacular Malecón con impresionantes puestas de sol, el faro natural más alto del mundo, el Carnaval con mayor tradición de México, cuna de la tradicional música de banda y el Centro Histórico más importante del noroeste de México, Mazatlán se considera un destino familiar de playa por excelencia con una hospitalidad y calidez tradicional para recibir al turista
					Disfrute y viva la cultura y tradiciones de esta ciudad que se fundó en los años 1500's, y que aún mantiene muchos de sus edificios históricos en su estilo arquitectónico original.
				</p>
				<p>
					Música, danza, teatro, ópera y muchas otras actividades culturales son parte del diario acontencer de la vida en Mazatlán, donde hay dos temporadas culturales muy importantes: el Festival Cultural Mazatlán, de octubre a diciembre, y el Festival de Primavera, de febrero a junio. El histórico teatro Ángela Peralta es el ícono de la cultura de Mazatlán.
				</p>
			</div>
		</div>
		<div class="col-md-7" id="contenido-nosotros-slider">
			<div id="rev_slider_6_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;max-height:646px;">
                <div id="rev_slider_6_1" class="rev_slider fullwidthabanner" style="display:none;max-height:646px;height:646px;">
                    <ul>
                        <li  data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan1.jpg" alt="bg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan2.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan3.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan4.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan5.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan6.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan7.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan8.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan9.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan10.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/mazatlan/mazatlan11.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                    </ul>
                    <div class="tp-bannertimer"></div>
                </div>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="texto">
				<h2>Centro Histórico</h2>
					<p>
					Da un paseo por el Centro Histórico. Ahí encontrarás la Plaza Machado, la Catedral y el teatro Ángela Peralta, el cual tiene el título de Patrimonio Histórico Nacional , Saborea su deliciosa gastronomía: aguachile, pescado zarandeado, tacos gobernador, tacos de marlin, callos de hacha, ceviche de serra y más. *RESTAURANTES: El Muchacho Alegre, El Torito, Pancho´s y La Costa Marinera O  Camina por el malecón, el segundo más largo del mundo. A lo largo de su recorrido, pasarás por restaurantes, bares, hoteles, monumentos y mucho más. NOTA: El transporte tradicional de Mazatlán es la Pulmonía , un vehículo "típico" para pasear por la zona dorada o el malecón. Puedes . Visitar el Acuario de Mazatlán, considerado como un de los más bonitos de México. Existe un espacio llamado la  "pecera oceánica" la cual es la mas grande de Latinoamérica. 
				</p>
				<h2>Playas</h2>
				<p>
					 Pasa una tarde en las mejores playas: Olas Altas, Playa Norte, Playa Gaviotas, Isla La Piedra, Playa Cerritos y más. Además, es típico escuchar música de banda o banda en vivo en algunas de las playas. Nota: Para Isla de la Piedra, es necesario tomar un pequeño barquito. 
				</p>
				<h2>Faro</h2>
				<p>
					 Sube al Faro de Mazatlán, considerado el segundo faro natural más alto del mundo. Se encuentra ubicado en la cima del Cerro del Crestón, donde disfrutarás las mejores vistas panorámicas de Mazatlán.
				</p>
				<h2>Islas</h2>
				<p>
					Conoce las tres islas (Isla Venados, Isla Pájaros e Isla Lobos). Las playas son tranquilas y puedes practicar snorkel, kayak y buceo. Estas tres islas promueven la conservación ecológica y son consideradas como centro ecológico. 
					Disfruta la vida nocturna, conoce la disco Valentino's, la más famosa de Mazatlán y realiza un recorrido por la gran variedad de bares y antros que existen en la zona del Malecón.
					 Asiste al Carnaval de Mazatlán, es el tercero más importante del mundo después del de Río de Janeiro y Nueva Orleáns. Se realiza cada año a mediados de febrero 
										</p>
				
			   </div>
		</div>
	</div>
	
</div>
<div class="row" id="contenido_sucursal_direccion">
		<h2>Sucursal Mazatlan</h2>
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="col-md-6">
				<i class="soap-icon-address"></i>
				<h3>Dirección</h3>
				<p>Carretera internacional norte km 120 Mazatlán, Sinaloa</p>
			</div>
			<div class="col-md-6">
				<i class="soap-icon-phone"></i>
				<h3>Teléfono</h3>
				<p> 01 (669) 983 32 32</p>
			</div>
		</div>
	</div>
<div class="mapa-extendido">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3666.4364507349187!2d-106.40247398560204!3d23.227199714479067!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x869f5306a65f62db%3A0x15621cce22e8a4ae!2sInternacional+120%2C+Loma+de+Ju%C3%A1rez%2C+Benito+Ju%C3%A1rez%2C+82180+Benito+Ju%C3%A1rez%2C+Sin.!5e0!3m2!1ses-419!2smx!4v1518890195601" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</div>
