<div class="header-fondo-culiacan escuinapa">
	<div class="">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Sucursal Escuinapa</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Sucursales - Escuinapa</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="mod_sucursal_culiacan">
	<div class="container" id="contenido-general-nosotros">
	<h1>ESCUINAPA</h1>
	<div class="row">
		<div class="col-md-5" id="contenido-nosotros-texto">
			<div class="texto">
				<p>La localidad de Escuinapa está situado en el Municipio de Escuinapa (en el Estado de Sinaloa). Hay 30790 habitantes. Escuinapa está a 18 metros de altitud.  En la localidad hay 15268 hombres y 15522 mujeres el 0,45% de la población es indígena, y el 0,16% de los habitantes habla una lengua indígena. El 0,00% de la población habla una lengua indígena y no habla español. Se tiene conocimiento de que los primeros pobladores de esta región fueron descendientes de la raza azteca, quienes aprovecharon la sal de las marismas, la caza y la pesca y se establecieron fundando un poblado de nombre Ahuchén. </p>
				<p>Los pobladores de Ahuchén abrumados por los mosquitos que trasmitían fiebre, la tierra salitrosa y el constante asedio de los piratas, se trasladaron a otro lugar al sur, y fundaron una comunidad que llamaron "Pueblo Viejo". Sin embargo, pronto se vieron en la necesidad de volver a emigrar por los constantes ataques de bandoleros. A poca distancia encontraron un lugar con mayor seguridad y formaron un nuevo pueblo que llamaron Izquinapa. </p>
			</div>
		</div>
		<div class="col-md-7" id="contenido-nosotros-slider">
			<div id="rev_slider_6_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;max-height:646px;">
                <div id="rev_slider_6_1" class="rev_slider fullwidthabanner" style="display:none;max-height:646px;height:646px;">
                    <ul>
                        <li  data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa1.jpg" alt="bg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa2.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa3.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa4.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa5.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa6.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa7.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/escuinapa/escuinapa8.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                    </ul>
                    <div class="tp-bannertimer"></div>
                </div>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="texto">
				<h2>Datos de Interés: </h2>
				<p>En 1602 había 20 vecinos en el poblado de Izquinapa hoy Escuinapa, pero no se registran sus nombres. 
				</p>
				<p>
				En 1912 se aprueba la Ley núm. 21 sobre la creación de municipalidades como forma interna del gobierno estatal, pero es hasta 1915 en que se suprimen las directorías políticas, cuando se erigen los primeros once municipios libres, siendo Escuinapa uno de ellos, creado por Decreto del 7 de septiembre de 1915 y ratificada su categoría en la Constitución de 1917
				</p>
				<p>El Puerto de Teacapan Ubicado al poniente del municipio, lugar que se distingue por la belleza natural que posee y las playas del litoral del pacífico; lo encontramos a 40 kilómetros de la cabecera municipal. Se caracteriza por su potencial turístico natural y su infraestructura y servicios de que dispone. </p>
				<p> La cercanía del municipio de Escuinapa con este polo de desarrollo y los atractivos propios de la región, permiten su integración al circuito turístico Mazatlán-Escuinapa-Teacapán. Como atractivo regional turístico se considera también la celebración del día del marino.  </p>
			   </div>
		</div>
	</div>
	
</div>
<div class="row" id="contenido_sucursal_direccion">
		<h2>Sucursal Escuinapa</h2>
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="col-md-6">
				<i class="soap-icon-address"></i>
				<h3>Dirección</h3>
				<p>Hidalgo y Morelos S/N Colonia Centro Escuinapa, Sinaloa C.P. 82400</p>
			</div>
			<div class="col-md-6">
				<i class="soap-icon-phone"></i>
				<h3>Teléfono</h3>
				<p> 01 (695) 953 48 05</p>
			</div>
		</div>
	</div>
<div class="mapa-extendido">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2186.4338695253177!2d-105.77492678898173!3d22.834723567617846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x869f1d860f72ef7d%3A0xfe04d71ca58ece63!2sCalle+Miguel+Hidalgo%2C+Escuinapa%2C+Sin.!5e0!3m2!1ses-419!2smx!4v1522954129931" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</div>
