<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Servicio de transporte</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Transporte</a></h4>
			</div>
		</div>
	</div>
</div>

<div class="container tour-detail-pageb contenido-servicios">
	<div class="row">
		<div id="main" class="col-md-8">
			<div class="post-1195 tour type-tour status-publish has-post-thumbnail hentry tour_type-honeymoon">
				<div class="image-box">
					<div class="flexslider photo-gallery style1" id="post-slideshow1" data-sync="#post-carousel1">
						<ul class="slides">
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria1.jpg" class="attachment-full" alt="10" />
							</li>
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria2.jpg" class="attachment-full" alt="9" />
							</li>
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria3.jpg" class="attachment-full" alt="8" />
							</li>
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria4.jpg" class="attachment-full" alt="6" />
							</li>
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria5.jpg" class="attachment-full" alt="3" />
							</li>
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria6.jpg" class="attachment-full" alt="2" />
							</li>		
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria7.jpg" class="attachment-full" alt="2" />
							</li>
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria8.jpg" class="attachment-full" alt="2" />
							</li>
							<li>
								<img width="900" height="500" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria9.jpg" class="attachment-full" alt="2" />
							</li>						
						</ul>
					</div>
					<div class="flexslider image-carousel style1" id="post-carousel1"  data-animation="slide" data-item-width="70" data-item-margin="10" data-sync="#post-slideshow1">
						<ul class="slides">
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria1.jpg" class="attachment-widget-thumb" alt="10" />
							</li>
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria2.jpg" class="attachment-widget-thumb" alt="9" />
							</li>
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria3.jpg" class="attachment-widget-thumb" alt="8" />
							</li>
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria4.jpg" class="attachment-widget-thumb" alt="6" />
							</li>
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria5.jpg" class="attachment-widget-thumb" alt="3" />
							</li>
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria6.jpg" class="attachment-widget-thumb" alt="2" />
							</li>	
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria7.jpg" class="attachment-widget-thumb" alt="2" />
							</li>	
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria8.jpg" class="attachment-widget-thumb" alt="2" />
							</li>
							<li>
								<img width="64" height="64" src="<?= Conectar::ruta_web()?>script/images/transporte/galeria9.jpg" class="attachment-widget-thumb" alt="2" />
							</li>						
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div id="texto-transporte" class="col-md-4">
			<h2 class="title title-transporte">
				AUS IRIZAR i6 VOLVO/SCANIA
			</h2>
			<div class="descripcion-transporte">
				<ul>
					<li> Autobuses I6 Irizar</li>
					<li> Unidades con 44 asientos reclinables.</li>
					<li> Habilitadas con pantallas HD de alta definición  de 22”</li>
					<li> Toma corriente</li>
					<li> Servicio de Internet a bordo por WIFI</li>
					<li> Cabina asilada</li>
					<li> Baños amplios </li>
				</ul>
			</div>
		</div>
	</div>
</div>
				
<div class="container seccion-links">
	<div class="row">
		<div class="col-md-12">
			<h2 class="subtitle-servicios">Vén y comprueba la calidad en nuestros servicios</h2>
		</div>
		<div class="col-md-6 contenido-link">
			<a href="" class="btn btn-link">Ir a la galería</a>
		</div>
		<div class="col-md-6 contenido-link">
			<a href="" class="btn btn-link">Contactar ahora</a>
		</div>
	</div>
	<div class="row" id="banner-youtube2">
		<div class="col-md-12">
			<a href="https://www.youtube.com/channel/UCMjrKoXHvPgFUZJRcYE_ANA" target="_blank" title="Autotransportes unidos de sinaloa">
				<img src="<?= Conectar::ruta_web()?>script/img_autotransportes/banner-youtube2.jpg" alt="">
			</a>
		</div>
	</div>
</div>