<div class="search-box-wrapper">
	<div class="search-box container">
		<div class="search-tab-content">
			<div id="tipo-pago" class="">
				<div id="tipo-terminos" class="">
					<div class="terminos">
						<h2>Términos y condiciones de venta</h2>
					</div>
					<form role="search" action="">
						<div class="row">
							<div class="form-group col-sm-4 col-md-4 ">
								<h4 class="title">Términos y condiciones</h4>
							</div>
							<div class="form-group col-sm-8 col-md-8 ">
								<h4 class="title"><strong>Boleto de abordar</strong></h4>
							</div>
							<div class="form-group col-sm-12 col-md-12 ">
								<ul>
									<li>1. Este es un boleto de abordar, por lo cual es su obligación el cuidado y conservación del mismo en buen estado, ya que es su seguro de viajero y le da derecho a 25kg. De equipaje Sin Costo</li>
									<li>2. Este bolete es válido únicamente para la fecha, hora, origen y destino, especificadas en el mismo.</li>
									<li>3. No hay CANCELACIONES, REEMBOLSOS y/o DEVOLUCIONES en este tipo de compra.</li>
									<li>4. Si desea realizar algún cambio en este boleto, sólo podrá efectuarlos en taquillas y/o puntos de venta directos, antes del día y hora del día, presentando una indentificación oficial además de este boleto.</li>
									<li>5. Deberá presentarse directamente en los andenes 30 minutos antes de su salida, con el boleto que emite este medio además de una identificación oficial (credencial de lector, licencia de manejo, cédula profesional o pasaporte vigentes, y en caso de estudiante,maestro o insen, su credencial vigente)</li>
									<li>6. Documente su equipaje 30 minutos antes de su salida.</li>
									<li>7. En caso de menores de edad, podrán abordar con la identificación del adulto que le acompañe.</li>
									<li>8. El pasajero acepta que la operación del autobús en el que se realiza el viaje amparado en el boleto, así como todo incidente, siniestro y cualquier responsabilidad deriva de la misma, frente a pasajeros o terceros sean de cualquier nacionalidad, tanto en su persona con sus bienes se rige por las leyes, disponibles, reglamentarias y normativas del país o Estado en donde ocurrieren los hechos.</li>
									<li>9. La empresa no se respoansabiliza por equipajes sin talon o por bultos u otras pertenencias de mano que el pasajero lleve consigo en el autobús, en caso de pérdida y/o extravío del equipaje documentado. Se pagará una indemnización hasta por el equivalente máximo a 20 días de salario mínimo general vigente en el D.F </li>
									<li>10. En territorio de los Estados Unidos Mexicanos, el boleto cumple con los requisitos del artículo 70 del Reglamento de Aunto Transporte Federal y Servicios Auxiliares y es comprobante que se expide de conformidad al Art. 37 del Reglamento del Código Físcal de la Federación, por las operaciones realizadas con el público en general. </li>
								</ul>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>


