<div class="search-box-wrapper">
	<div class="search-box container">
		<div class="search-tab-content">
			<div id="tipo-servicios" class="">
				<div class="seleccion-asiento ">
					<h2>Selección de asiento</h2>
				</div>
				<div class="col-sm-12 col-md-12 col-offset-12 ">
					<img  src="<?= Conectar::ruta_web()?>script/images/img/selec-asiento.png "class="img-responsive" alt="Cinque Terre" width="50%" height="236" >
				</div>
			</div>
		</div>
	</div>
</div>