<!DOCTYPE html>
<html lang="es">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <head>
        <title>Seleccion tu asiento</title>
        <?php require_once("view/includes/script_header.phtml"); ?>
    </head>
    <body class="home page page-id-785 page-template page-template-templates page-template-template-home page-template-templatestemplate-home-php wpb-js-composer js-comp-ver-4.9.1 vc_responsive">
        <div id="page-wrapper">
            <?php require_once("view/includes/header.phtml"); ?>
            <section id="content" class="no-padding">
                <?php require_once("view/seleccion_asiento/asientos.phtml"); ?>
            </section>
            <?php require_once("view/includes/footer.phtml"); ?>
        </div>
        <div class="opacity-overlay opacity-ajax-overlay"><i class="fa fa-spinner fa-spin spinner"></i></div>
        <?php require_once("view/includes/script_footer.phtml"); ?>
    </body>
</html>
