<footer id="footer" class="style-def">
            <div class="footer-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-md-4">
                            <div id="travcontactwidget-3" class="contact-box small-box widget_travcontactwidget">
                                <h2 class="widgettitle">Acerca de nosotros</h2>
                                <p>En Autotransportes Unidos de Sinaloa somos una empresa de Autobuses Foráneos en el Estado de Sinaloa.</p>
                                <p>Contamos con autobuses de primera clase, garantizando la comodidad y seguridad de nuestros pasajeros. </p>

                                <a class="btn btn-info-nosotros" href="<?= Conectar::ruta_web() ?>nosotros/">Ver más <i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
                                <address class="contact-details"><span class="contact-phone"><i class="soap-icon-phone"></i> 1-800-123-456</span>
                                    <br /><a class="contact-email" href="mailto:hello@travelo.com">contacto@autotransporteaus.com</a></address>
                            </div>
                            <div id="social_links-widget-3" class="small-box social_links">
                                <ul class="social-icons clearfix">
                                    <li class="twitter"><a title="twitter" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-twitter"></i></a></li>
                                    <li class="googleplus"><a title="googleplus" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-googleplus"></i></a></li>
                                    <li class="facebook"><a title="facebook" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-facebook"></i></a></li>
                                    <!--<li class="linkedin"><a title="linkedin" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-linkedin"></i></a></li>-->
                                    <li class="youtube"><a title="youtube" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-youtube"></i></a></li>
                                     <li class="instagram"><a title="instagram" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-instagram"></i></a></li>
                                    <li class="pinterest"><a title="pinterest" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-pinterest"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <div id="trav-nav_menu-widget-2" class="small-box widget_nav_menu">
                                <h2 class="widgettitle">Mapa de sitio</h2>
                                <div class="menu-footer-menu-container">
                                    <ul id="menu-footer-menu" class="row">
                                        <li><a href="<?= Conectar::ruta_web() ?>"><i class="icon-menu flaticon-casa"></i> Inicio</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>nosotros/"><i class="soap-icon-friends soap-footer"></i> Nosotros</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>#destinos-inicio"><i class="icon-menu flaticon-maleta"></i> Destinos</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>#venta-linea"><i class="icon-menu flaticon-boleto"></i> Boletos</a></li>
                                        <li><a href=""><i class="icon-menu flaticon-factura"></i> Facturación</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>#promociones-inicio"><i class="icon-menu flaticon-promociones"></i> Promociones</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>galeria/"><i class="soap-icon-slider soap-footer"></i> Galería</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>#mapa-sucursales"><i class="icon-menu flaticon-ubicacion"></i> Sucursales</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>aviso-de-privacidad/"><i class="soap-icon-stories soap-footer"></i> Aviso de privacidad</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>politicas-y-obligaciones/"><i class="soap-icon-stories soap-footer"></i> Políticas y obligaciones</a></li>
                                        <li><a href="<?= Conectar::ruta_web() ?>contacto/"><i class="icon-menu flaticon-telefono"></i> Contacto</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4" id="formulario_contacto">
                            <div id="modify-search-panel" data-spy="scroll" class="panel-collapse collapse in" style="height: auto;">
                                <div class="panel-content">
                                    <form role="search" method="get" id="searchform" class="acc-searchform">
                                        <h2>Queremos saber tu opiniónes</h2>
                                        <div class="form-group row">
                                            <label class="title-form"><span>1. </span>En general, ¿cómo calificaría la calidad de nuestro servicio?</label>
                                            <label class="sub-label">Taquillas</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-taquilla="mala" value=""> Mala</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-taquilla="buena" value=""> Buena</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-taquilla="excelente" value=""> Excelente</label> 

                                            <label class="sub-label">Edecán</label>  
                                            <label class="col-md-4 label-option"><input type="checkbox" data-edecan="mala" value=""> Mala</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-edecan="buena" value=""> Buena</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-edecan="excelente" value=""> Excelente</label>                                         
                                            <label class="sub-label">Equipajero</label> 
                                            <label class="col-md-4 label-option"><input type="checkbox" data-equipajero="mala" value=""> Mala</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-equipajero="buena" value=""> Buena</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-equipajero="excelente" value=""> Excelente</label>                                          
                                            <label class="sub-label">Conductor</label> 
                                            <label class="col-md-4 label-option"><input type="checkbox" data-conductor="mala" value=""> Mala</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-conductor="buena" value=""> Buena</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-conductor="excelente" value=""> Excelente</label>                                          
                                        </div>
                                        <div class="form-group row">
                                            <label class="title-form"><span>2. </span>¿A través de qué medio conoce nuestro servicio?</label>
                                            
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="mala" value=""> Publicidad</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="buena" value=""> Periódico</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="excelente" value=""> Radio</label> 
                                            
                                              
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="mala" value=""> Twitter</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="buena" value=""> Facebook</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="excelente" value=""> Espectacular</label>                                         
                                            
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="mala" value=""> Youtube</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="buena" value=""> Recomendación</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="excelente" value=""> Email</label>                                          
                                            
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="mala" value=""> Punto de venta</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="buena" value=""> Televisión</label>
                                            <label class="col-md-4 label-option"><input type="checkbox" data-medio="excelente" value=""> Revistas</label>                                          
                                        </div>
                                        <button class="btn-medium btn-enviar-opinion uppercase full-width">Enviar </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
            <div class="bottom gray-area">
                <div class="container">
                    <div class="pull-right">
                        <a id="back-to-top" href="#"><i class="soap-icon-longarrow-up circle"></i></a>
                    </div>
                    <div class="copyright pull-right">
                        <p><a href="//webazteca.com.mx" target="_blank" title="web azteca">&copy; Web Azteca</a></p>
                    </div>
                </div>
            </div>
        </footer>