 <header id="header" class="navbar-static-top">
            <div class="topnav hidden-xs">
                <div class="container">
                    <!-- <ul class="quick-menu pull-left">
                        <li><a href="#travelo-login" class="soap-popupbox">MY ACCOUNT</a></li>
                        <li class="ribbon">
                            <a href="#" title="">usd</a>
                            <ul class="menu mini">
                                <li class="active"><a href="indexa011.html?selected_currency=usd" title="United States Dollar">USD</a></li>
                                <li><a href="indexbcc0.html?selected_currency=eur" title="Euro">EUR</a></li>
                                <li><a href="indexa1b8.html?selected_currency=rub" title="Russian Ruble">RUB</a></li>
                            </ul>
                        </li>
                        <li class="ribbon">
                            <a href="#">English</a>
                            <ul class="menu mini">
                                <li class="active"><a href="http://www.soaptheme.net/wordpress/travelo" title="English">English</a></ul>
                            </li>
                    </ul> -->
                    
                    <ul class="quick-menu pull-right">
                        <li>
                            <a href="tel://" class="button yellow btn-small" style="height: 30px; font-size: 1em">
                                 LLamar ahora !
                            </a>
                        </li>
                        <!-- <li><a href="#travelo-login" class="soap-popupbox">LOGIN</a></li> -->
                    </ul>
                    <ul class="quick-menu pull-right">
                        <li class="twitter">
                            <a title="twitter" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-twitter"></i></a>
                        </li>
                        <li class="googleplus">
                            <a title="googleplus" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-googleplus"></i></a>
                        </li>
                        <li class="facebook">
                            <a title="facebook" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-facebook"></i></a>
                        </li>
                        <li class="youtube">
                            <a title="youtube" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-youtube"></i></a>
                        </li>
                        <li class="pinterest">
                            <a title="pinterest" href="" target="_blank" data-toggle="tooltip"><i class="soap-icon-pinterest"></i></a>
                        </li>
                               
                    </ul>
                </div>
            </div>
            <div id="main-header">
                <div class="main-header">
                    <a href="#mobile-menu-01" data-toggle="collapse" class="mobile-menu-toggle">
                Mobile Menu Toggle
             </a>
             <div class="container" id="logo-central">
                <div class="row">
                     <div class="col-md-12 col-xs-10 contenedor-logo-central">
                        <h1 class="logo navbar-brand">
                            <a href="<?= Conectar::ruta_web()?>">
                                <img src="<?= Conectar::ruta_web()?>script/images/logo/logo_central.png" alt="Autotransportes unidos de sinaloa" />
                            </a>
                        </h1>
                     </div>
                </div>
             </div>
                    <div class="container-fluid" id="contenedor-menu">
                        
                        <nav id="main-menu" class="menu-main-menu-container">
                            <ul id="menu-main-menu" class="menu">
                                <li id="menu-item-1108" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-785 current_page_item current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor menu-item-has-children menu-item-1108">
                                    <a href="<?= Conectar::ruta_web() ?>"><i class="icon-menu flaticon-casa"></i> Inicio</a>
                                   
                                </li>
                                <li id="menu-item-657" class="menu-item menu-item-type-custom menu-item-object-travel_guide  menu-item-657 ">
                                    <a href="<?= Conectar::ruta_web() ?>#destinos-inicio"><i class="icon-menu flaticon-maleta"></i> Destinos</a>
                                    
                                </li>
                                <li id="menu-item-1314" class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305">
                                    <a href="<?= Conectar::ruta_web() ?>#venta-linea"><i class="icon-menu flaticon-boleto"></i> Boletos</a>
                                </li>
                                <li id="menu-item-1818" class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305">
                                    <a href=""><i class="soap-icon-user soap-footer"></i> Servicios</a>
                                    <ul class="sub-menu ">
                                        <li id="menu-item-1105" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-785 current_page_item menu-item-1105"><a href="<?= Conectar::ruta_web() ?>transporte/">Transporte</a></li>
                                        <li id="menu-item-1104" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1104"><a href="<?= Conectar::ruta_web() ?>paqueteria/">Paquetería y envíos</a></li>
                                    </ul>
                                </li>
                                <li id="menu-item-659" class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305">
                                    <a href=""><i class="icon-menu flaticon-factura"></i> Facturación</a>
                                </li>
                                <li id="menu-item-699" class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305">
                                    <a href="<?= Conectar::ruta_web() ?>#promociones-inicio"><i class="icon-menu flaticon-promociones"></i> Promociones</a>
                                </li>
                                <li id="menu-item-656" class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305">
                                    <a href="<?= Conectar::ruta_web() ?>galeria/"><i class="soap-icon-slider soap-footer"></i> Galería</a>
                                </li>
                                <li id="menu-item-658" class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305">
                                    <a href="<?= Conectar::ruta_web() ?>#mapa-sucursales"><i class="icon-menu flaticon-ubicacion"></i> Sucursales</a>
                                    <ul class="sub-menu ">
                                        <li id="menu-item-1105" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-785 current_page_item menu-item-1105"><a href="<?= Conectar::ruta_web() ?>culiacan/">Culiacan</a></li>
                                        <li id="menu-item-1104" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1104"><a href="<?= Conectar::ruta_web() ?>mazatlan/">Mazatlan</a></li>
                                        <li id="menu-item-1104" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1104"><a href="<?= Conectar::ruta_web() ?>rosario/">Rosario</a></li>
                                        <li id="menu-item-1104" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1104"><a href="<?= Conectar::ruta_web() ?>escuinapa/">Escuinapa</a></li>
                                    </ul>
                                </li>
                                <li id="menu-item-1305" class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305">
                                    <a href="<?= Conectar::ruta_web() ?>contacto/"><i class="icon-menu flaticon-telefono"></i> Contacto</a>
                                </li>
                                
                            </ul>
                        </nav>
                    </div>
                    <!-- .container -->
                </div>
                <!-- .main-header -->
            </div>
            <!-- #main-header -->
            <!-- mobile menu -->
            <nav id="mobile-menu-01" class="mobile-menu collapse">
                <ul id="mobile-primary-menu" class="menu">
                    <li class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1108"><a href="<?= Conectar::ruta_web() ?>">Inicio</a>
                        
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-657"><a href="<?= Conectar::ruta_web() ?>#destinos-inicio">Destinos</a>
                        
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1269"><a href="<?= Conectar::ruta_web() ?>#venta-linea">Boletos</a>
                       
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-1271"><a href="">Servicios</a>
                        <ul class="sub-menu">
                            <li class="menu-item menu-item-type-post_type menu-item-object-page  menu-item-1435"><a href="<?= Conectar::ruta_web() ?>transporte/">Transporte</a>
                                
                            </li>
                            <li class="menu-item menu-item-type-custom menu-item-object-custom  menu-item-1298"><a href="<?= Conectar::ruta_web() ?>paqueteria/">Paquetería y envíos</a>
                                
                            </li>
                        </ul>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-travel_guide menu-item-1305"><a href="">Facturación</a></li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1273"><a href="<?= Conectar::ruta_web() ?>#promociones-inicio">Promociones</a>
                    </li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom  menu-item-1306"><a href="<?= Conectar::ruta_web() ?>galeria/">Galería</a>
                    </li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom  menu-item-1308"><a href="<?= Conectar::ruta_web() ?>#mapa-sucursales">Sucursales</a>
                    </li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom  menu-item-1310"><a href="<?= Conectar::ruta_web() ?>contacto/">Contacto</a>
                    </li>
                </ul>
                <!-- <ul class="mobile-topnav container">
                    <li><a href="#travelo-login" class="soap-popupbox">MY ACCOUNT</a></li>
                    <li><a href="#travelo-login" class="soap-popupbox">LOGIN</a></li>
                    <li class="ribbon currency menu-color-skin"><a href="#" title="usd">usd</a>
                        <ul class="menu mini">
                            <li class="active"><a href="indexa011.html?selected_currency=usd" title="United States Dollar">USD</a></li>
                            <li><a href="indexbcc0.html?selected_currency=eur" title="Euro">EUR</a></li>
                            <li><a href="indexa1b8.html?selected_currency=rub" title="Russian Ruble">RUB</a></li>
                        </ul>
                    </li>
                    <li class="ribbon menu-color-skin"><a href="#">English</a>
                        <ul class="menu mini">
                            <li class="active"><a href="" title="English">English</a></ul>
                        </li>
                        <li><a href="https://themeforest.net/item/travelo-traveltour-booking-wordpress-theme/9806696?ref=SoapTheme" style="font-size: 1em;background: #e9b02b !important; margin: 10px; padding: 12px 20px; text-transform: uppercase; opacity:1"><i class="soap-icon-shopping"></i> Purchase</a></li>
                </ul> -->
            </nav>
            <!-- mobile menu -->
        </header>