<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Servicio de paquetería y envíos</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Paquetería y envíos</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="container" id="paqueteria-envio">
	<div class="row">
		<div class="col-md-6 descripcion-paque">
			<div class="texto-paq">
				<p>En autotransportes unidos de sinaloa contamos con el servicio  de Mensajería y Paquetería ligera  , un servicio de alta calidad. Somos su mejor opcion  confiable y con presencia, únicos en el pacifico mexicano con salidas cada 20 minutos, siendo asi de los mas rapidos en llevar sus paquetes a su destino ; contamos  con  flotilla de autobuses mas grande y moderna para trasladar sus paquetes.
				Contamos con la mayor variedad de horarios a su disposición, su mensajería se enviará en la corrida más próxima disponible.
				</p>
				<p>
					La documentación es 100% automatizada, de esta manera poder darle seguimiento oportuno desde la recepción hasta la entrega, con la seguridad de que sus paquetes llegarán a su destino.
				</p>
			</div>
			
		</div>
		<div class="col-md-6 img-paqueteria">
			<img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/PAQUETERIAAUS1.jpg" alt="">
		</div>
		<div class="col-md-12 contacto-paqueteria ">
			<div class="large-block">
				<div class="vc_row wpb_row vc_inner row">
					<div class="wpb_column col-sm-6 col-md-4">
						<div class="vc_column-inner ">
							<div class="wpb_wrapper">
								<div class="icon-box style3 counters-box">
									<div class="numbers">
										<i class="fa fa-phone"></i>
										<span class="display" >Culiacán</span>
									</div>
									<div class="description">
										01 (667) 714 11 91
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="wpb_column col-sm-6 col-md-4">
						<div class="vc_column-inner ">
							<div class="wpb_wrapper">
								<div class="icon-box style3 counters-box">
									<div class="numbers">
										<i class="fa fa-phone"></i>
										<span class="display" >La cruz</span>
									</div>
									<div class="description">
										01 (669) 3668 5912
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="wpb_column col-sm-6 col-md-4">
						<div class="vc_column-inner ">
							<div class="wpb_wrapper">
								<div class="icon-box style3 counters-box">
									<div class="numbers">
										<i class="fa fa-phone"></i>
										<span class="display" >Mazatlán</span>
									</div>
									<div class="description">
										01 (669) 983 91 93
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="clearfix"></div>
					<div class="wpb_column col-sm-6 col-md-4 col-md-offset-2">
						<div class="vc_column-inner ">
							<div class="wpb_wrapper">
								<div class="icon-box style3 counters-box">
									<div class="numbers">
										<i class="fa fa-phone"></i>
										<span class="display" >El rosario</span>
									</div>
									<div class="description">
										01 (664) 114 02 46
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="wpb_column col-sm-6 col-md-4 ">
						<div class="vc_column-inner ">
							<div class="wpb_wrapper">
								<div class="icon-box style3 counters-box">
									<div class="numbers">
										<i class="fa fa-phone"></i>
										<span class="display" >Escuinapa</span>
									</div>
									<div class="description">
										01 (695) 953 48 05
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="one-half wpb_column col-sm-12">
			<div class="vc_column-inner ">
				<div class="wpb_wrapper">
					<div>
						<h2>Más información</h2>
					</div> 
					<div class="toggle-container style1" id="trav-tgg-599b51694d0ba">
						<div class="panel">
							<h4 class="panel-title">
								<a href="#ocurrre" data-toggle="collapse" data-parent="#trav-tgg-599b51694d0ba" class="collapsed">Ocurre<span class="open-sub" <="" span=""></span></a>
							</h4>
							<div id="ocurrre" class="panel-collapse collapse" style="height: 0px;">
								<div class="panel-content">
		
									<div class="texto-interno-tab">
										<p>Ocurre es el servicio de mensajería y paquetería en el que el cliente debe ir a los módulos a realizar su envío, y el destinatario debe recogerlo en la terminal destino.</p>
											<p>A través Ocurre usted puede hacer envíos de refacciones, herramientas,  ropa, documentos, recipientes no rompibles, cables, etc., debidamente flejados y sellados perfectamente.</p>
										<p>El contenido queda en responsabilidad total del remitente .</p>
									</div> 
								</div>
							</div>
						</div> 

						<div class="panel">
							<h4 class="panel-title">
								<a href="#objetos-prohibidos" data-toggle="collapse" class="collapsed" data-parent="#trav-tgg-599b51694d0ba">Objetos prohibidos <span class="open-sub" <="" span=""></span></a>
							</h4>
							<div id="objetos-prohibidos" class="panel-collapse collapse" style="height: 0px;">
								<div class="panel-content">
									<div class="texto-interno-tab">
										<div class="row">
											<div class="col-md-6 lista-prohibidos">
												<ul>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Animales vivos y muertos.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Pieles y cuero de animal.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Dinero en efectivo.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Instrumentos negociables para el portador.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Cheques de caja o viajero.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Tarjetas de crédito o débito.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Documentos legales oficiales o notariados.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Productos o materiales piratas o falsificados.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Materiales inflamables, explosivos o tóxicos.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Solventes o Corrosivos.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Drogas.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Narcóticos ilegales.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Armas de fuego.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Partes de la mismas armas.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Armas blancas.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Municiones.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Equipo militar y pertenecientes a instituciones policiaca de cualquier indole.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Restos humanos (incluyendo cenizas).</li>
													
												</ul>
											</div>
											<div class="col-md-6 lista-prohibidos">
												<ul>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Pornografía.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Artículos de dudosa procedencia.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Objetos prohibidos por cualquier ley federal estatal o local.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Bebidas alcohólicas.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Animales.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> vegetales.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Plantas y sus productos que se encuentren en peligro de extinción.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Antigüedades u obras de arte.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Artículos de una colección.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Aparatos electrónicos como ( Celulares, Laptops, Tablet ).</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Medicamentos o productos farmacéuticos controlados o de circulación restringida.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Muestras medicas.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Artículos perecederos.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Diamantes industriales.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Carbones.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Metales preciosos.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Piedras.</li>
													<li><i class="fa fa-circle" aria-hidden="true"></i> Relojes y joyería.</li>
												</ul>
											</div>
										</div>
									</div> 
								</div>
							</div>
						</div> 

						<div class="panel">
							<h4 class="panel-title">
								<a href="#requisitos" data-toggle="collapse" class="collapsed" data-parent="#trav-tgg-599b51694d0ba">Requisitos para realizar y recoger el envío <span class="open-sub" <="" span=""></span></a>
							</h4>
							<div id="requisitos" class="panel-collapse collapse" style="height: 0px;">
								<div class="panel-content">
									<div class="texto-interno-tab">
										<p>Para documentar:</p>
										<ul>
											<li><i class="fa fa-minus" aria-hidden="true"></i> El remitente debe presentar una identificación oficial con fotografía vigente.</li>
											
										</ul>
										<p>Para recoger el envío</p>
										<ul>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Número de Guía.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> El destinatario debe presentar una identificación oficial con fotografía vigente.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Si se desea recoger un envío no siendo el destinatario designado en la carta de porte, se debe presentar una carta poder autorizada y firmada por el remitente o destinatario, anexando la identificación de quien otorga el poder y de quien lo recibe.</li>

									</div> 
								</div>
							</div>
						</div> 
						<div class="panel">
							<h4 class="panel-title">
								<a href="#rastrear-paquete" data-toggle="collapse" class="collapsed" data-parent="#trav-tgg-599b51694d0ba">Rastrea tu paquete<span class="open-sub" <="" span=""></span></a>
							</h4>
							<div id="rastrear-paquete" class="panel-collapse collapse" style="height: 0px;">
								<div class="panel-content">
									<div class="texto-interno-tab">
										<h4>Próximamente</h4>

									</div> 
								</div>
							</div>
						</div> 
						<div class="panel">
							<h4 class="panel-title">
								<a href="#guias-prepagadas" data-toggle="collapse" class="collapsed" data-parent="#trav-tgg-599b51694d0ba">Guías prepagadas<span class="open-sub" <="" span=""></span></a>
							</h4>
							<div id="guias-prepagadas" class="panel-collapse collapse" style="height: 0px;">
								<div class="panel-content">
									<div class="texto-interno-tab">
										<h4>Próximamente</h4>

									</div> 
								</div>
							</div>
						</div> 
						<div class="panel">
							<h4 class="panel-title">
								<a href="#tipos-de-envios" data-toggle="collapse" class="collapsed" data-parent="#trav-tgg-599b51694d0ba">Tipos de envíos<span class="open-sub" <="" span=""></span></a>
							</h4>
							<div id="tipos-de-envios" class="panel-collapse collapse" style="height: 0px;">
								<div class="panel-content">
									<div class="texto-interno-tab">
										<ul>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Sobres.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Paquetes de 0-1 KG.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Cajas desde 1-30 KG. VOLUMEN MÁXIMO EN SU ENVÍO 65 X 50 X 55.</li>
										</ul>
									</div> 
								</div>
							</div>
						</div> 
						<div class="panel">
							<h4 class="panel-title">
								<a href="#cobertura" data-toggle="collapse" class="collapsed" data-parent="#trav-tgg-599b51694d0ba">Cobertura<span class="open-sub" <="" span=""></span></a>
							</h4>
							<div id="cobertura" class="panel-collapse collapse" style="height: 0px;">
								<div class="panel-content">
									<div class="texto-interno-tab">
										<ul>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Culiacán.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> La cruz de Elota.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Mazatlán.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> El rosario.</li>
											<li><i class="fa fa-minus" aria-hidden="true"></i> Escuinapa.</li>
										</ul>

									</div> 
								</div>
							</div>
						</div> 
					</div>
				</div>
			</div>
		</div>
	</div>		
</div>