<div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="destinos-inicio">
    <div class="container tab-container clearfix">
        <div class="row ">
          <div class="title col-md-12  ">
            <h1>Cónoce nuestros destinos</h1>
          </div>
          <div class="col-md-6 tabs clearfix">
            <div class="row">
              <div class="col-md-6 img-destinos" >
                <a href="#modalCuliacan" data-toggle="tab">
                  <div class="img-des">
                      <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/culiacan.jpg" class="attachment-widget-thumb wp-post-image" alt="1" />
                      <div class="titulo-des">
                        <h2>
                          Culiacán
                        </h2>
                      </div>
                  </div> 
                </a>
              </div>
              <div class="col-md-6 img-destinos" >
                <a href="#modalMazatlan" data-toggle="tab">
                  <div class="img-des">
                    <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/mazatlan.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                    <div class="titulo-des">
                        <h2>
                          Mazatlán
                        </h2>
                      </div>
                  </div>
                </a>
              </div>
              <div class="col-md-6 img-destinos" >
                <a href="#modalElrosario" data-toggle="tab">
                  <div class="img-des">
                    <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/el_rosario.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                    <div class="titulo-des">
                          <h2>
                            El rosario
                          </h2>
                    </div>
                  </div>
                </a>
              </div>
              <div class="col-md-6 img-destinos" >
                <a href="#modalEscuinapa" data-toggle="tab">
                  <div class="img-des">
                      <img width="100%" src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagina/escuinapa.jpg" class="attachment-widget-thumb wp-post-image" alt="2" />
                      <div class="titulo-des">
                        <h2>
                          Escuinapa
                        </h2>
                      </div>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-6 tab-content">
            <div id="modalCuliacan" class="tab-pane fade active in">
              <div>
                  <h4>
                    Culiacán</h4>
                  <div class="parte1">
                    <p>
                      Culiacán oficialmente es conocido como Culiacán Rosales, es una ciudad que se encuentra ubicada al noroeste de México, capital y ciudad mas grande del estado de Sinaloa tiene una población de 755 510 habitantes (2010).
                       Culiacán es una de las ciudades mas visitadas de Sinaloa por sus bellos alrededores, sus lugares históricos, por sus fiestas populares, sus artesanías y por sus costumbres y tradiciones.
                    </p>
                    <p>
                      Algunas de los lugares mas visitados por los turistas y las personas son :
                      <ul>
                        <li>Jardín Botánico Culiacán.</li>
                        <li>Zoológico Culiacán.</li>
                        <li>Parque Las Riberas.</li>
                        <li>Iglesia La Lomita.</li>
                        <li>Santuario y historia.</li>
                        <li>Parque Constitución.</li>
                        <li>Puente Negro.</li>
                        <li>Museo de Arte de Sinaloa.</li>
                      </ul>
                    </p>
                    </div>
                </div> 
                <a href="<?= Conectar::ruta_web()?>culiacan/" class="vermasinformacion">Ver Más</a>
            </div>
            <div id="modalMazatlan" class="tab-pane fade">
              <div>
                  <h4>Mazatlán</h4>
                  <div class="parte1">
                    <p>Reconocido por sus 20 kilómetros de cálidas playas, exquisita gastronomía de fama internacional, 7 kilómetros de espectacular Malecón con impresionantes puestas de sol, el faro natural más alto del mundo, el Carnaval con mayor tradición de México, cuna de la tradicional música de banda y el Centro Histórico más importante del noroeste de México, Mazatlán se considera un destino familiar de playa por excelencia con una hospitalidad y calidez tradicional para recibir al turista.</p>
                    <p>La "Perla del Pacífico" rodeada de lugares históricos, riquísima gastronomía y extraordinarias playas.</p>
                    <p>Disfrute y viva la cultura y tradiciones de esta ciudad que se fundó en los años 1500's, y que aún mantiene muchos de sus edificios históricos en su estilo arquitectónico original.</p>
                    <p>Música, danza, teatro, ópera y muchas otras actividades culturales son parte del diario acontencer de la vida en Mazatlán</p>
                  </div>
              </div> 
                <a href="<?= Conectar::ruta_web()?>mazatlan/" class="vermasinformacion">Ver Más</a>
            </div>
            <div id="modalElrosario" class="tab-pane fade">
              <div>
                  <h4>El rosario</h4>
                  <div class="parte1">
                    <p>El nombre de esta población del estado de Sinaloa, corresponde tanto a su población más importante, como también para el municipio entero. Se localiza en la región sur del territorio sinaloense. Limita al norte con los municipios de Mazatlán y de Concordia; por el sur colinda con Escuinapa y el estado de Nayarit; al oriente con el territorio duranguense, y al poniente con las aguas del Océano Pacífico.</p>
                    <p>La fundación de la ciudad tuvo lugar el día 3 de agosto de 1655. Este evento está rodeado de una interesante anécdota. En tal fecha un caporal, Bonifacio Rojas, se dio cuenta de que le faltaba una res y fue a buscarla. Avanzó por el río hasta llegar a la Loma de Santiago. Allí encontró a la res que se le había escapado. Como se había hecho de noche, Rojas decidió encender una fogata. Al día siguiente, tras despertarse, se llevó una gran sorpresa: mientras removía los restos de la fogata, descubrió una enorme cantidad de plata fundida, pegada a una peña. Antes de dar apresurado aviso de su hallazgo a su patrón, el caporal resolvió dejar un rosario para identificar el sitio que había encontrado.</p>
                  </div>
              </div>
                  <a href="<?= Conectar::ruta_web()?>rosario/" class="vermasinformacion">Ver Más</a>
            </div>
            <div id="modalEscuinapa" class="tab-pane fade">
              <div>
                  <h4>Escuinapa</h4>
                  <div class="parte1">
                    <p>La localidad de Escuinapa está situado en el Municipio de Escuinapa (en el Estado de Sinaloa). Hay 30790 habitantes. Escuinapa está a 18 metros de altitud. En la localidad hay 15268 hombres y 15522 mujeres el 0,45% de la población es indígena, y el 0,16% de los habitantes habla una lengua indígena. El 0,00% de la población habla una lengua indígena y no habla español.</p>
                    <p>Se tiene conocimiento de que los primeros pobladores de esta región fueron descendientes de la raza azteca, quienes aprovecharon la sal de las marismas, la caza y la pesca y se establecieron fundando un poblado de nombre Ahuchén. </p>
                    <p>Los pobladores de Ahuchén abrumados por los mosquitos que trasmitían fiebre, la tierra salitrosa y el constante asedio de los piratas, se trasladaron a otro lugar al sur, y fundaron una comunidad que llamaron "Pueblo Viejo". Sin embargo, pronto se vieron en la necesidad de volver a emigrar por los constantes ataques de bandoleros. A poca distancia encontraron un lugar con mayor seguridad y formaron un nuevo pueblo que llamaron Izquinapa. </p>
                  </div>
              </div>
                <a href="<?= Conectar::ruta_web()?>escuinapa/" class="vermasinformacion">Ver Más</a>
            </div>
          </div>
        </div>
    </div>
</div>

<script>
  jQuery(document).ready(function(){ 
       jQuery('.tab-pane #vermas').toggle(
           // Primer click
        function(e){ 
           jQuery('.parte2').slideDown();
           jQuery('html,body').animate({
                    scrollTop: jQuery(".parte2").offset().top
        }, 500);
           jQuery(this).text('Ver menos');
            e.preventDefault();
        }, // Separamos las dos funciones con una coma
      
        // Segundo click
        function(e){ 
           jQuery('.parte2').slideUp();
           jQuery('html,body').animate({
                    scrollTop: jQuery(".parte1").offset().top
        }, 500);
           jQuery(this).text('Ver más');
            e.preventDefault();
        }
        );
   });
</script>
