<!DOCTYPE html>
<html lang="es" prefix="og: http://ogp.me/ns#">
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <head>
        <title>AUS - Autotransportes Unidos de Sinaloa</title>
        <?php require_once("view/includes/script_header.phtml"); ?>
    </head>
    <body class="home page page-id-785 page-template page-template-templates page-template-template-home page-template-templatestemplate-home-php wpb-js-composer js-comp-ver-4.9.1 vc_responsive">
        <div id="page-wrapper">
            <?php require_once("view/includes/header.phtml"); ?>
            <div id="slideshow">
                <?php require_once("view/index/slider.phtml"); ?>
            </div>
            <section id="content" class="no-padding">
                <?php require_once("view/index/formularios.phtml"); ?>
                <div class="entry-content">
                    <div class="vc_row wpb_row row">
                        <div class="col-sm-12 ">
                            <?php require_once("view/index/seccion5.phtml"); ?>
                            <?php require_once("view/index/seccion4.phtml"); ?>
                            <?php require_once("view/index/destinos.phtml"); ?>
                            <?php require_once("view/index/seccion3.phtml"); ?>
                            <?php require_once("view/index/seccion7.phtml"); ?>
                            <?php require_once("view/index/promociones.phtml"); ?>
                        </div>
                    </div>
                </div>
            </section>
            <?php require_once("view/includes/footer.phtml"); ?>
        </div>        
        <?php require_once("view/includes/script_footer.phtml"); ?>
    </body>
</html>