<div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="aus-card">
    <div class="container-fluid" id="fondo-afiliate">
        <div class="row ">
           <div class="col-md-6 col-md-offset-3">
            <div class="texto">
                <h2>Afiliate a nuestro programa de lealtad y obtén increíbles beneficios.</h2>
            </div>
            <div class="button-afiliarse">
                <a href="<?= Conectar::ruta_web() ?>afiliarse/" title="" class="btn " id="btn-afiliarse">Afiliese aquí <i class="fa fa-arrow-right" aria-hidden="true"></i> </a>
            </div>
               <img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/aus-card-banner3.png" alt="">
            
           </div>
        </div>
    </div>
</div>