<div class="parallax global-map-area" id="mapa-sucursales" data-stellar-background-ratio="0.5">
    <div class="promo-box honeymoon">
        <div class="container">
            <div class="col-md-12 animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="">
                <div class="row">
                    <div class="col-md-12 title-map">
                        <h1 class="title">Encuentra la sucursal más cercana</h1>
                    </div>
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/">
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                Culiacán
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/" >
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                La cruz
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/" >
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2">
                            <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                Mazatlán
                            </div>
                        </a>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-4 col-md-offset-2 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/" >
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                El rosario
                            </div>
                        </a>
                    </div>
                    
                    <div class="col-md-4 mapa-contenido">
                        <a href="<?= Conectar::ruta_web() ?>contacto/">
                            <div class="icon-map animated"  data-animation-type="bounce" data-animation-duration="2">
                                <i class="flaticon-ubicacion"></i>
                            </div>
                            <div class="text-map">
                                Esquinapa
                            </div>
                        </a>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>