<div class="container-fluid" id="cintilla-pagos">
    <div class="container">
        <div class="row">
            <div class="col-md-3 title-pagos">
                <h1>Aceptamos: </h1>
            </div>
            <div class="col-md-9 img-pagos-contenido">
                <div class="icon-pago">
                    <ul>
                        <li>
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagos/logos/visa.png" alt="">
                        </li>
                        <li>
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagos/logos/mastercard.png" alt="">
                        </li>
                        <li>
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagos/logos/american.png" alt="">
                        </li>
                        <li>
                            <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/pagos/logos/paypal.png" alt="">
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="vc_row wpb_row vc_inner vc_row-fluid offer vc_custom_1459450325173 inner-container">
    <div class="container">
        <div class="row">
            <div class="wpb_column col-sm-12">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <div>
                            <h1 class="text-center">¿Por qué viajar con nosotros?</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="image-box style2">
    <div class="vc_row wpb_row vc_inner vc_row-fluid offer vc_custom_1459450367450 inner-container">
        <div class="container">
            <div class="row">
                <div class="wpb_column col-sm-12 col-md-6">
                    <div class="vc_column-inner ">
                        <a href="" title="" data-toggle="modal" data-target="#modalviaje">
                            <div class="wpb_wrapper">
                                <article class="box">
                                    <figure>
                                       <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/viajerapido/portada_viajerapido.jpg" alt="imageframe-image" width="270" height="192" class="animated" data-animation-type="fadeInLeft" data-animation-duration="" data-animation-delay="" />
                                    </figure>
                                    <div class="details">
                                        <h4>Viaje rápido y seguro</h4>
                                    </div>
                                </article>
                            </div>
                        </a>
                    </div> 
                </div>
                <div class="wpb_column col-sm-12 col-md-6">
                    <div class="vc_column-inner ">
                        <a href="" title="" data-toggle="modal" data-target="#modaloperadores">
                            <div class="wpb_wrapper">
                                <article class="box">
                                    <figure>
                                        <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/operadorescapacitados/portada_operador.jpg" alt="imageframe-image" width="270" height="192" class="animated" data-animation-type="fadeInLeft" data-animation-duration="" data-animation-delay="0.4" />
                                    </figure>
                                    <div class="details">
                                        <h4>Operadores capacitados</h4>
                                    </div>
                                </article>
                            </div>
                         </a>
                    </div>
                </div>
                <div class="wpb_column col-sm-12 col-md-6">
                    <div class="vc_column-inner ">
                        <a href="" title="" data-toggle="modal" data-target="#modalpaqueteria">
                            <div class="wpb_wrapper">
                                <article class="box">
                                    <figure>
                                        <img src="<?= Conectar::ruta_web()?>script/img_autotransportes/beneficios/paqueteria.jpg" alt="imageframe-image" width="270" height="192" class="animated" data-animation-type="fadeInLeft" data-animation-duration="" data-animation-delay="" />
                                    </figure>
                                    <div class="details">
                                        <h4>Paquetería y mensajería</h4>
                                    </div>
                                </article>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="wpb_column col-sm-12 col-md-6">
                    <div class="vc_column-inner ">
                        <a href="" title="" data-toggle="modal" data-target="#modalinstalaciones">
                            <div class="wpb_wrapper">
                                <article class="box">
                                    <figure>
                                        <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/instalaciones/portada_instalaciones.jpg" alt="imageframe-image" width="270" height="192" class="animated" data-animation-type="fadeInLeft" data-animation-duration="" data-animation-delay="0.4" />
                                    </figure>
                                    <div class="details">
                                        <h4>Instalaciones de calidad</h4>
                                    </div>   
                                </article>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade modal-ubicaciones" id="modalviaje" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Viaje rápido y seguro</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div  class="col-md-6 img-modal-porque">
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                              <li data-target="#myCarousel" data-slide-to="1"></li>
                              <li data-target="#myCarousel" data-slide-to="2"></li>
                              <li data-target="#myCarousel" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner">
                              <div class="item active">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/viajerapido/viajerapido1.jpg" alt="" style="width:100%;">
                              </div>

                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/viajerapido/viajerapido2.jpg" alt="" style="width:100%;">
                              </div>           
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/viajerapido/viajerapido3.jpg" alt="" style="width:100%;">
                              </div>
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/viajerapido/viajerapido4.jpg" alt="" style="width:100%;">
                              </div>
                            </div>

                            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                              <span class="glyphicon glyphicon-chevron-left"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                              <span class="glyphicon glyphicon-chevron-right"></span>
                              <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6 texto-modal-porque">
                        <p>Con Nuestra moderna flota usted viaja cómodo y seguro hacia su destino, nos aseguramos que su trayecto sea toda una experiencia placentera, olvidándose de cualquier inconveniente y  sentirse seguro con el desempeño de nuestros autobuses que  entregan una sensación de poder y seguridad, reléjese disfrutando una buena película en las mega  pantallas HD de nuestras unidades o navegue por internet a la más alta velocidad 4G LTE conexión  Telcel®.  Q</p>
                        <h2>Que tenga un Feliz Viaje!!!</h2>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade modal-ubicaciones" id="modaloperadores" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Operadores capacitados</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-7 img-modal-porque">
                        <div id="myCarousel2" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                              <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
                              <li data-target="#myCarousel2" data-slide-to="1"></li>
                              <li data-target="#myCarousel2" data-slide-to="2"></li>
                              <li data-target="#myCarousel2" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner">
                              <div class="item active">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/operadorescapacitados/operador1.jpg" alt="" style="width:100%;">
                              </div>

                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/operadorescapacitados/operador2.jpg" alt="" style="width:100%;">
                              </div>
                            
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/operadorescapacitados/operador3.jpg" alt="" style="width:100%;">
                              </div>
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/operadorescapacitados/operador4.jpg" alt="" style="width:100%;">
                              </div>
                            </div>
                            <a class="left carousel-control" href="#myCarousel2" data-slide="prev">
                              <span class="glyphicon glyphicon-chevron-left"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel2" data-slide="next">
                              <span class="glyphicon glyphicon-chevron-right"></span>
                              <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-5 texto-modal-porque">
                        <p>Operadores responsables  y dedicados con vocación de servicio,  este es el personal humano que complementa nuestra  dedicación al giro de autotransporte, comprometidos con la calidad y amabilidad, temple que da seguridad y confianza a nuestros pasajeros.</p>
                    </div>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade modal-ubicaciones" id="modalpaqueteria" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Paquetería y  mensajería</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div  class="col-md-6 img-modal-porque">
                        <div id="myCarousel5" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                              <li data-target="#myCarousel5" data-slide-to="0" class="active"></li>
                              <li data-target="#myCarousel5" data-slide-to="1"></li>
                              <li data-target="#myCarousel5" data-slide-to="2"></li>
                              <li data-target="#myCarousel5" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner">
                              <div class="item active">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/paqueteria/paqueteria4.jpg" alt="" style="width:100%;">
                              </div>
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/paqueteria/paqueteria2.jpg" alt="" style="width:100%;">
                              </div>           
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/paqueteria/paqueteria3.jpg" alt="" style="width:100%;">
                              </div>
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/paqueteria/paqueteria1.jpg" alt="" style="width:100%;">
                              </div>
                            </div>
                            <a class="left carousel-control" href="#myCarousel5" data-slide="prev">
                              <span class="glyphicon glyphicon-chevron-left"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel5" data-slide="next">
                              <span class="glyphicon glyphicon-chevron-right"></span>
                              <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6 texto-modal-porque">
                        <p>En autotransportes unidos de sinaloa contamos con el servicio  de Mensajería y Paquetería ligera  , un servicio de alta calidad. </p>
                        <a href="<?= Conectar::ruta_web()?>paqueteria/" title="" class="btn btn-modal btn-default btn-paqueteria-modal"> Más información</a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade modal-ubicaciones" id="modalinstalaciones" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title">Instalaciones de calidad</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6 img-modal-porque">
                        <div id="myCarousel3" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                              <li data-target="#myCarousel3" data-slide-to="0" class="active"></li>
                              <li data-target="#myCarousel3" data-slide-to="1"></li>
                              <li data-target="#myCarousel3" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                              <div class="item active">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/instalaciones/instalaciones1.jpg" alt="" style="width:100%;">
                              </div>

                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/instalaciones/instalaciones2.jpg" alt="" style="width:100%;">
                              </div>
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/instalaciones/instalaciones3.jpg" alt="" style="width:100%;">
                              </div>
                              <div class="item">
                                <img src="<?= Conectar::ruta_web()?>script/images/inicio/viajaconnosotros/instalaciones/instalaciones4.jpg" alt="" style="width:100%;">
                              </div>
                            </div>
                            <a class="left carousel-control" href="#myCarousel3" data-slide="prev">
                              <span class="glyphicon glyphicon-chevron-left"></span>
                              <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel3" data-slide="next">
                              <span class="glyphicon glyphicon-chevron-right"></span>
                              <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6 texto-modal-porque">
                        <p>Con terminales propias en la mayoría de nuestros destinos , instalaciones cómodas  y con todos  los servicios contamos con una amplia y cómoda sala de espera, cafetería, baños gratuitos, estacionamiento y servicio de taxi de los proveedores locales, en Culiacán la nueva central internacional de autobuses millenium  le ofrece sus cómodas instalaciones con la calidad que usted  merece .</p>
                    </div>
                </div>  
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>