<div class="vc_row wpb_row vc_inner vc_row-fluid section destinations inner-container" id="servicios-a-bordo">
    <div class="container">
        <div class="row">
            <div class="wpb_column col-sm-12 animated" data-animation-type="fadeInUp" data-animation-duration="2" data-animation-delay="">
                <div class="vc_column-inner ">
                    <div class="wpb_wrapper">
                        <h1 class="title">Servicios a bordo</h1>
                        <div class="row hotel image-box listing-style2">
                            <div class="col-md-12">
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                            <i class="flaticon-asiento-camion"></i> 
                                        </div>
                                        <div class="text-servicios">
                                            <h2>Asientos reclinables</h2> 
                                        </div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title=""  class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios" class="link-servicios-a-bordo">
                                        <div class="icon">
                                        <i class="flaticon-pantalla"></i></div>
                                        <div class="text-servicios"><h2>Mega pantallas HD</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-musica"></i></div>
                                        <div class="text-servicios"><h2>Música</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-wifi"></i></div>
                                        <div class="text-servicios"><h2>Conexión wifi</h2></div>
                                    </div>
                                </a>
                            </div>
                            <div class="col-md-12 ">
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-pelicula"></i></div>
                                        <div class="text-servicios"><h2>Películas</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-sanitarios"></i></div>
                                        <div class="text-servicios"><h2>Sanitarios</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-conexion"></i></div>
                                        <div class="text-servicios"><h2>Conexiones eléctricas</h2></div>
                                    </div>
                                </a>
                                <a href="<?= Conectar::ruta_web() ?>servicios-a-bordo/" title="" class="link-servicios-a-bordo">
                                    <div class="col-md-3 icon-servicios">
                                        <div class="icon">
                                        <i class="flaticon-cafeteria"></i>
                                        </div>
                                        <div class="text-servicios"><h2>Luz de lectura</h2></div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




