<div class="header-fondo-culiacan rosario">
	<div class="">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Sucursal Rosario</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Sucursales - Rosario</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="mod_sucursal_culiacan">
	<div class="container" id="contenido-general-nosotros">
	<h1>ROSARIO</h1>
	<div class="row">
		<div class="col-md-5" id="contenido-nosotros-texto">
			<div class="texto">
				<p>El nombre de esta población del estado de Sinaloa, corresponde tanto a su población más importante, como también para el municipio entero. Se localiza en la región sur del territorio sinaloense. Limita al norte con los municipios de Mazatlán y de Concordia; por el sur colinda con Escuinapa y el estado de Nayarit; al oriente con el territorio duranguense, y al poniente con las aguas del Océano Pacífico. 
					La fundación de la ciudad tuvo lugar el día 3 de agosto de 1655. Este evento está rodeado de una interesante anécdota. En tal fecha un caporal, Bonifacio Rojas, se dio cuenta de que le faltaba una res y fue a buscarla. Avanzó por el río hasta llegar a la Loma de Santiago. Allí encontró a la res que se le había escapado. Como se había hecho de noche, Rojas decidió encender una fogata. Al día siguiente, tras despertarse, se llevó una gran sorpresa: mientras removía los restos de la fogata, descubrió una enorme cantidad de plata fundida, pegada a una peña. Antes de dar apresurado aviso de su hallazgo a su patrón, el caporal resolvió dejar un rosario para identificar el sitio que había encontrado.				</p>
			</div>
		</div>
		<div class="col-md-7" id="contenido-nosotros-slider">
			<div id="rev_slider_6_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" style="margin:0px auto;background-color:#E9E9E9;padding:0px;margin-top:0px;margin-bottom:0px;max-height:646px;">
                <div id="rev_slider_6_1" class="rev_slider fullwidthabanner" style="display:none;max-height:646px;height:646px;">
                    <ul>
                        <li  data-transition="fade" data-slotamount="7" data-masterspeed="1000" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario1.jpg" alt="bg1" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario2.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario3.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario4.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario5.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario6.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario7.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario8.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario9.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario10.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario11.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario12.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario13.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                        <li data-transition="slidedown" data-slotamount="7" data-masterspeed="1500" data-saveperformance="off">
                            <img src="<?= Conectar::ruta_web()?>script/images/destinos/rosario/rosario14.jpg" alt="bg2" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat">
                        </li>
                    </ul>
                    <div class="tp-bannertimer"></div>
                </div>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="texto">
				<p>					El patrón, entusiasmado por lo que había descubierto su caporal, corrió donde estaba el rosario para comprobarlo y al ver la plata, realizó un tajo en la peña y comenzó la explotación de este metal precioso. Eso derivó en el nacimiento de la ciudad del Rosario.</p>
				<h2>Qué visitar en El Rosario Pueblo Magico</h2>
					<p>
					Actualmente El Rosario es un Pueblo Mágico que ha sabido mantenerse vivo. Se encuentra a unos 70 kilómetros del puerto de Mazatlán. De entre las figuras más relevantes de El Rosario hay que mencionar a la cantante vernácula Lola Beltrán, quien tuvo un enorme  cariño por esta comunidad de Sinaloa. Algunas importantes comunidades de la región son las de Pozole, Chameta, Agua Verde, Los Ojitos y Niebla. Son sitios de gran interés turístico, para conocer la actividad ganadera, pesquera y agrícola que definen a esta zona del país.<br>
					Estamos en un territorio donde se percibe en gran medida la influencia de los antiguos totorames, indígenas que habitaron en la zona donde colinda Sinaloa con el estado de Durango. Se trata de un destino turístico que cuenta con un clima muy grato y un rico ecosistema.<br>
 					De entre los tesoros turísticos del Pueblo Mágico de El Rosario se deben mencionar los siguientes: la Iglesia de Nuestra Señora de El Rosario, la Casa de Lola Beltrán y el Museo de la Cultura Totorame, en Chametla.

				</p>
				<h2>Playas</h2>
				<p>
					 También son imperdibles las playas de El Caimanero, la bella laguna de Iguanero, el centro histórico de El Rosario, las minas del Tajo y el Malecón del Río Baluarte.
				</p>
				<h2>Información relevante</h2>
				<p>
					A lo largo de los siglos XVIII y XIX El Rosario fue un significativo centro minero. En 1700 este Pueblo Mágico fue sede de los poderes del área de California, Baja California y Sonora. Durante un buen tiempo fue una especie de ciudad- asilo y a esta población se le debe en mucho, la importancia que Mazatlán alcanzó como puerto. Por aquellos años San Blas, en el estado de Nayarit, era el puerto más relevante de la región, puesto que por allí se enviaba la mayor parte del Mineral que se obtenía de El Rosario. Por tal motivo, en 1800, se incrementó el apoyo para que Mazatlán también ayudara como puerto de salida de las embarcaciones cargadas de plata y oro.

				</p>
				<h2>Actividades a Realizar</h2>
				<p>
					La celebración típica más importante de El Rosario es la que se realiza para festejar a la Virgen del Rosario. Esta última tiene lugar el primer domingo de octubre. También es interesante y de gran convocatoria, la Feria de la Primavera, uno de los eventos en su tipo con mayor antigüedad en México, la cual tiene lugar del 1 al 10 de mayo. Además, como parte de un viaje a El Rosario, conviene conocer las pintorescas comunidades indígenas de Matatán y Cacalotán, en las cuales también se realizan notables celebraciones populares.

				</p>
				
			   </div>
		</div>
	</div>
	
</div>
<div class="row" id="contenido_sucursal_direccion">
		<h2>Sucursal Rosario</h2>
		<div class="col-md-12" id="contenido-nosotros-texto">
			<div class="col-md-6">
				<i class="soap-icon-address"></i>
				<h3>Dirección</h3>
				<p>Luis Donaldo Colosio S/N colonia centro, El rosario, Sinaloa</p>
			</div>
			<div class="col-md-6">
				<i class="soap-icon-phone"></i>
				<h3>Teléfono</h3>
				<p>01 (694) 114 02 46</p>
			</div>
		</div>
	</div>
<div class="mapa-extendido">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3672.7600832632743!2d-105.86063688560645!3d22.995848223098267!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x869f219ea0ed0675%3A0xbaf8cbe2153a2728!2sLuis+Donaldo+Colosio+Murrieta%2C+El+Rosario%2C+Sin.!5e0!3m2!1ses-419!2smx!4v1518890392873" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</div>
