<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Acerca de nosotros</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Nosotros</a></h4>
			</div>
		</div>
	</div>
</div>

<div class="container" id="contenido-general-nosotros">
	<div class="row">
		<div class="col-md-6" id="contenido-nosotros-texto">
			<div class="texto">
				<h2>¿Quiénes somos?</h2>
				<p>En Autotransportes Unidos de Sinaloa somos una empresa de Autobuses Foráneos en el Estado de Sinaloa.</p>

				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> Contamos con autobuses de primera clase, garantizando la comodidad y seguridad de nuestros pasajeros.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Tenemos una gran flotilla en los destinos de Culiacán, La Cruz, Mazatlán, Rosario y Escuinapa en el momento que usted lo necesite.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Ofrecemos salidas cada 20 minutos, con lo cual garantizamos que se llegará al destino en el menor tiempo posible.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Nuestros operadores y todo el personal que labora en Autotransportes Unidos de Sinaloa nos caracterizamos por nuestro amable y cordial trato a nuestros usuarios.</li>
				</ul>  
			</div>
		</div>
		<div class="col-md-6" id="contenido-nosotros-slider">
			<img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/AUSEQUPO.jpg" alt="">
		</div>
	</div>
	
	<div class="row">
		<div class="block">
			<div class="image-box style6">
				<div class="vc_row wpb_row vc_inner row">
					<div class="wpb_column col-sm-12 col-md-5">
						<div class="vc_column-inner ">
							<div class="wpb_wrapper">
								<article class="box">
									<figure class="middle-block middle-block-auto-height" style="position: relative; height: 145px;">
										<img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/autobus-img/redimensionadas/autobus-11.jpg">
									</figure>
								</article>
							</div>
						</div>
					</div>
					<div class="wpb_column col-sm-12 col-md-7">
						<div class="vc_column-inner ">
							<div class="">
								<article class="box">
									<div class="details">
										<h2 class="box-title">Misión</h2>
										<div>Somos una empresa de transporte de pasajeros con más de 25 años de presencia estatal, que brindan servicios que nos diferencian por tener salidas constantes, ofreciendo puntualidad soportada por personal altamente calificado con unidades con el confort y la seguridad requerida.</div>
									</div>
								</article>
							</div>
						</div>
					</div>
				</div>
				<div class="vc_row wpb_row vc_inner row">
					<div class="wpb_column col-sm-12 col-md-7">
						<div class="vc_column-inner ">
							<div class="">
								<article class="box">
									<div class="details">
										<h2 class="box-title">Visión</h2>
										<div>Mantener el liderazgo estatal en el servicio de transporte continuo, modernizando constantemente las unidades y asegurando que nuestro personal trabaja permanentemente en elevar la satisfacción del usuario, y en lograr la expansión de nuestros servicios a otros destinos. </div>
									</div>
								</article>
							</div>
						</div>
					</div>
					<div class="wpb_column col-sm-12 col-md-5">
						<div class="vc_column-inner ">
							<div class="wpb_wrapper">
								<article class="box">
									<figure class="middle-block middle-block-auto-height" style="position: relative; height: 145px;">
										<a href="#" title="">
											<img src="<?= Conectar::ruta_web() ?>script/img_autotransportes/autobus-img/redimensionadas/autobus-1.jpg">
										</a>
									</figure>
								</article>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row" id="valores-nosotros">
		<h2 class="box-title">Nuestros valores</h2>
		<div class="col-md-3 mision-vision brown">
			<a href="#" class="button btn-extra " target="_self">
				<div class="icon-wrap">
					<i class="fa fa-heart" aria-hidden="true"></i>
				</div>
				<span>
					<em>Respeto</em>
				</span>
			</a>
			<div class="text">
				<p>Mantener un nivel de respeto y cordialidad mutua entre el personal y los clientes, buscando entablar siempre una relación adecuada.</p>
			</div>
		</div>
		<div class="col-md-3 mision-vision brown">
			<a href="#" class="button btn-extra yellow" target="_self">
				<div class="icon-wrap">
					<i class="fa fa-gavel" aria-hidden="true"></i>
				</div>
				<span>
					<em>Compromiso</em> 
				</span>
			</a> 
			<div class="text">
				<p>Buscar siempre el bienestar de nuestros pasajeros y colaboradores conduciéndonos siempre de manera ética y profesional.</p>
			</div>
		</div>
		<div class="col-md-3 mision-vision brown">
			<a href="#" class="button btn-extra" target="_self">
				<div class="icon-wrap">
					<i class="fa fa-user" aria-hidden="true"></i>
				</div>
				<span>
					<em>Responsabilidad</em>
				</span>
			</a>
			<div class="text">
				<p>Cumplir con nuestro deber organizacional haciendo siempre lo correcto y buscando el cumplimiento de nuestras responsabilidades bajo los lineamientos morales de nuestra institución,</p>
			</div>
		</div>
		<div class="col-md-3 mision-vision brown">
			<a href="#" class="button btn-extra yellow" target="_self">
				<div class="icon-wrap">
					<i class="fa fa-thumbs-up" aria-hidden="true"></i>
				</div>
				<span>
					<em>Honestidad</em> 
				</span>
			</a> 
			<div class="text">
				<p>Actuar y trabajar de manera responsable, y profesional regido siempre bajo las normas éticas de conducta teniendo como principal objetivo el  beneficio de nuestros clientes y colaboradores.</p>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="col-md-3 mision-vision brown">
			<a href="#" class="button btn-extra" target="_self">
				<div class="icon-wrap">
					<i class="fa fa-certificate" aria-hidden="true"></i>
				</div>
				<span>
					<em>Confianza</em>
					
				</span>
			</a>
			<div class="text">
				<p>Brindar nuestro servicio y seguridad a nuestros clientes y colaboradores basándonos en el cumplimineto de nuestros compromisos, trabajando con responsabilidad con personal altamente calificado.</p>
			</div>
		</div>
		<div class="col-md-3 mision-vision brown">
			<a href="#" class="button btn-extra yellow" target="_self">
				<div class="icon-wrap">
					<i class="fa fa-users" aria-hidden="true"></i>
				</div>
				<span>
					<em>Trabajo en equipo</em> 
				</span>
			</a> 
			<div class="text">
				<p>Entendemos que nuestros colaboradores son la fuerza principal de nuestra institución, por lo que buscamos siempre el bienestar y la promoción de un clima laboral positivo para poder proyectarlo a nuestros clientes.</p>
			</div>
		</div>
		<div class="col-md-3 mision-vision brown">
			<a href="#" class="button btn-extra " target="_self">
				<div class="icon-wrap">
					<i class="fa fa-cog" aria-hidden="true"></i>
				</div>
				<span>
					<em>Espíritu de servicio</em>
				</span>
			</a>
			<div class="text">
				<p>Contamos con la disposición de ofrecer a nuestros clientes y colaboradores un trato amable, apoyo, servicio de calidad, eficiencia y respuesta oportuna a las necesidades que se presenten.</p>
			</div> 
		</div>
		
		
	</div>
</div>

<div class="container seccion-links">
	
	<div class="row" id="banner-youtube2">
		<div class="col-md-12">
			<a href="https://www.youtube.com/channel/UCMjrKoXHvPgFUZJRcYE_ANA" target="_blank" title="Autotransportes unidos de sinaloa">
				<img src="<?= Conectar::ruta_web()?>script/img_autotransportes/banner-youtube2.jpg" alt="">
			</a>
		</div>
	</div>
</div>

