<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Términos y Condiciones</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Términos y Condiciones</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="container" id="politicas-y-obligaciones">
	<div class="row">
		<div class="col-md-12">
			<div class="text">
				<h4 class="sub-title">Términos y condiciones</h4>
				<p>Bienvenido al sitio web de AUS, una empresa conduciéndose al futuro, para brindarte un mejor servicio es importante lea los términos y condiciones  antes de utilizar el sitio <a target="_blank" href="http://www.unidosdesinaloa.com.mx">www.unidosdesinaloa.com.mx</a></p>
				<p>Autotransportes unidos de Sinaloa no se hace responsable por retrasos en horarios de servicio, por condiciones ajenas a las operaciones fortuitos y/o fuerza mayor.</p>
				<h3>Compra de boletos:</h3>
				<p></p>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>
						Para comprar boleto están disponibles las terminales de Autotransportes unidos de Sinaloa de nuestra cobertura, los puntos de venta establecidos en nuestra cobertura y en la página web  <a target="_blank" href="http://www.unidosdesinaloa.com.mx">www.unidosdesinaloa.com.mx</a></li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Si durante el proceso de compra tiene algún problema o duda, comunicarse al 01 800 6unidos (01 800 6864367), donde con gusto le atenderemos.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Al realizar la compra por internet debe pasar a ventanilla con el boleto o comprobante de pago para que se asigne la unidad que está por salir y abordarla</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Es obligación del pasajero el traer su boleto, ya que es su seguro de viajero y le da derecho a 25kg de equipaje sin costo extra.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Todo el equipaje extra a los 25kg será canalizado al área de paquetería, para que pueda definir el costo de traslado de equipaje.</li>
				</ul>
				<h3>Recomendación de compra en línea:</h3>		
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Es importante tomar en cuenta que si va utilizar el último servicio del día de nuestros horarios establecidos, debe presentarse en taquilla por lo menos 20 minutos antes de su salida, por afluencia de gente es la única corrida que puede salir antes de la hora indicada. </li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Si el usuario no aborda el autobús en la fecha de compra del boleto sencillo se perderá sin rembolso y sin responsabilidad para la empresa.</li>
				</ul>
				<h3>Compra de boleto viaje redondo</h3>		
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Usted podrá adquirir su boleto abierto con la opción de escogerlo sin fecha, ni hora programada. </li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Este tipo de boleto cuenta con una vigencia de 3 meses a partir de la fecha de su compra y queda sujeto a disponibilidad de asientos.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>El boleto solo tendrá validez si esta legible y con la vigencia de 3 meses después de la fecha de emisión. Le recordamos que si extravía el boleto tendrá que adquirir uno nuevo, sin responsabilidad para la empresa autotransportes unidos de Sinaloa.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Los boletos de promoción viaje redondo serán válidos si corresponden a al origen-destino del viaje, si es diferente no podrá utilizarlo y se tendrá que adquirir un boleto nuevo.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Los boletos abiertos pueden ser pagados en su totalidad con tarjeta bancaria.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Para confirmar el boleto abierto tiene que pasar a taquillas presentando su boleto para que sea asignada la unidad próxima a salir. </li>
					<li><i class="fa fa-square" aria-hidden="true"></i></li>
				</ul>
				<h3>AUS ofrece los siguientes descuentos:</h3>		
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Descuento de Menor</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Descuento de INAPAM</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Descuento Persona con discapacidad </li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Descuento Estudiante y  Maestro
				</ul>
				<br>
				<p>Las tarifas de descuentos serán publicadas en cada una de las terminales de AUS y en la página web  <a target="_blank" href="http://www.unidosdesinaloa.com.mx">www.unidosdesinaloa.com.mx</a></p>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Al presentar su boleto o comprobante de pago por página de internet es necesario pasar a taquilla y presentarlo junto con su identificación para amparar el descuento, de lo contrario pagara la diferencia del valor total del boleto.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>En caso de NO presentar su identificación no se podrá aplicar el descuento correspondiente en taquilla y se pagara la diferencia del valor total del boleto sin descuento.</li>
				</ul>
				<h3>Formas de pago</h3>		
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Pago en taquilla de nuestras terminales y por internet aplica con tarjeta bancaria débito y crédito (Visa o Mastercard), excepto American Express.</li>
				</ul>
				<h3>AUS ofrece los siguientes descuentos:</h3>		
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Por seguridad, no se permite que ningún menor de 16 años viaje solo, deberá estar acompañado en todo momento por un adulto.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>No podrán a bordar el autobús, los clientes que se encuentren bajo el influjo de alcohol, drogas enervantes o que porten elementos que son un riesgo para los usuarios.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Se consideran menores de 4 a 12 años de edad; los menores de 4 años no pagan boleto, viajando en el mismo asiento que el adulto.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>De 4 años a 12 años ocupan asiento. Por lo tanto pagan boleto de menor que ampara su seguro de viajero.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i></li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Los pasajeros registrados con descuento de INAPAM, deberán mostrar la credencial expedida por esta institución al llegar a taquilla para acreditar el descuento y asignar la unidad para abordar, de no presentarla se le cobrará la diferencia del costo total del boleto.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Los descuentos de estudiante y maestro, solo se otorgarán presentando credencial con fotografía vigente y que los acredite como tal, de no presentarla al momento de pasar a taquilla se le cobrará la diferencia del costo total del boleto.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Con la finalidad de apoyar la educación AUS hace un descuento permanente para los estudiantes y maestros que aplica los 365 días del año</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>El descuento de “pcd” (persona con discapacidad) soló se otorgara presentando credencial expedida por el DIF vigente que los acredite como tal. de no presentarla al momento de la compra y/o al momento de abordar se le cobrará la diferencia del costo total del boleto.</li>
				</ul>
				<h3>Restringidos:</h3>		
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Para la transportación de mascotas, estos deberán ir en jaulas y preferentemente sedados; los cuales viajarán en la cajuela de equipaje del autobús.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>No se permite viajar con animales en el interior del autobús (solo mascotas guía autorizada y certificada)</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Las personas con discapacidad visual acompañadas de su perro guía o de asistencia. Debe presentar los documentos que lo certifiquen como credencial vigente.</li>
				</ul>
				<h3>Políticas de equipaje</h3>		
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>La entrega del equipaje se realizara al cliente con la entrega del ticket, en caso contrario no será entregada.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Es responsabilidad del usuario exigir y conservar la entrega del ticket ya que en caso de extravío o pérdida la empresa no se hará responsable ni estará obligado para en caso de que persona diferente  recoja su maleta exhibiendo el ticket.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>La empresa no se hace responsable del extravió o daño de objetos de valor ingresados como equipaje en las unidades.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Para en caso de pérdida o extravió del equipaje la empresa se responsabiliza a cubrir y así lo expresa en el ticket lo contemplado en el artículo 66 fracción V de la ley de caminos, puentes y autotransporte federal el equivalente a 15 salarios mínimo general en el distrito federal.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>En caso de pérdida o extravió del boleto de viajero la empresa no se hace responsable de su reembolso y esta queda bajo resguardo y responsabilidad del usuario.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>La empresa no responde por equipaje sin talón o por bultos u otras pertenencias de mano que el pasajero lleve consigo en el interior del autobús.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>En perdida o extravió la procedencia de la indemnización solo será válida por el ticket otorgado del equipaje.</li>
				</ul>
				<br><strong>Los objetos no permitidos para traslado en nuestras unidades son los siguientes</strong><br><br>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Químicos Peligrosos;</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Armas de Fuego;</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Mascotas (Excepto que estén documentadas, en jaulas especiales o que sean mascotas entrenadas para asistencia a personas con capacidades especiales [Con su respectivo certificado]);</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Gases inflamables;</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Drogas</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Material Radiactivo</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Órganos y/o restos humanos o animales</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Frutas y Hortalizas (de Sur a Norte).</li>
				</ul>
				<br><strong>Facturación</strong><br><br>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Para facturar deberá ingresar al link facturación en línea o directamente a www.ausfacturacion.com</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Recuerde que por disposición oficial usted puede facturar sus boletos a lo largo del mes que lo compro, una vez concluido el mes, usted cuenta con 5 días para facturar.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Si durante el proceso de facturación usted tiene algún problema o duda, comunicarse al 01 800 6unidos (01 800 6864367), donde con gusto le atenderemos.</li>
				</ul>
			</div>
		</div>
	</div>
</div>