<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Preguntas y Respuestas</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Preguntas y respuestas</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="container" id="politicas-y-obligaciones">
	<div class="row">
		<div class="col-md-12">
			<div class="text">
				<h4 class="sub-title">
					¿Para qué sirve la Tarjeta AUSCARD?
				</h4>
				<p>La Tarjeta AUSCARD es parte del programa de recompensas de AUS, la cual agradece tu confianza y premia tu preferencia con grandes beneficios</p>
				<h4 class="sub-title">
					¿Para qué sirve la Tarjeta AUSCARD?
				</h4>
				<p>Son varios los beneficios que obtienes al registrarte en el programa de recompensas de AUS:</p>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Recibes bonificaciones de viaje hacia cualquiera de nuestros destinos.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Promociones especiales por tu cumpleaños.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Acceso a promociones y beneficios especiales.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Recibe promociones SORPRESA vía mail y celular.</li>
				</ul>
				<h4 class="sub-title">
					¿Cómo funciona el sistema de recompensas AUS?
				</h4>
				<p>PASOS A SEGUIR :</p>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Primero tienes que ir y adquirir tu tarjeta AUSCARD a cualquiera de nuestras sucursales.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Realizas la activación de tu tarjeta en cualquiera de nuestras taquillas o a través de www.unidosdesinaloa.</li>com.mx/auscard o al 01 (800) 6864-367 , crearás un usuario y contraseña con los cuales puedes consultar tus puntos, historial y promociones exclusivas para ti.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Una vez registrada, al realizar tu primer viaje, se te comenzará a realizar el acummulado de puntos.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>En cada viaje que realizas con nosotros, presenta tu tarjeta AUSCARD, ya que obtendrás el acumulado de puntos correspondientes entre otros beneficios.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i>Utiliza tus viajes acumulados para viajar GRATIS hacia cualquiera de nuestros destinos.</li>
				</ul>
				<h4 class="sub-title">
					¿Todos los viajes generan puntos?
				</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>No, recuerda que para ser acreedor del acumulado de puntos no deberás de gozar de cualquier otra de las promociones publicadas por AUS (Descuentos para maestros y estudiantes, descuentos INAPAM, descuento de viaje redondo, entre otros).
					</li>
				</ul>
				<h4 class="sub-title">
					¿Qué vigencia tiene la tarjeta AUS?
				</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>Si tu tarjeta no tiene movimientos en un periodo de 12 meses automáticamente se da de baja del programa de recompensas AUS.
					</li>
				</ul>
				<h4 class="sub-title">
				¿Dónde puedo adquirirla?
				</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i>•	En la central AUS participante más cercana.
					</li>
				</ul>
				<h4 class="sub-title">¿Qué tengo que hacer para adquirirla?</h4>
				<ul>
				<li><i class="fa fa-square" aria-hidden="true"></i>
					Solicitarla en el área de taquilla de nuestras instalaciones en tu siguiente viaje en AUS y registrarte mediante cualquiera de los medios: punto de venta en taquilla, página web o teléfono. Si no registras tu tarjeta, no recibe beneficios.</li>
				</ul>
				<h4 class="sub-title">¿La tarjeta tiene algún costo?</h4>
				<ul>
				<li><i class="fa fa-square" aria-hidden="true"></i>
					No, en caso de ser su primera tarjeta, para reposición la tarjeta tiene un costo de $20.</li>
				</ul>
				<h4 class="sub-title">¿Cómo hago la reposición de mi tarjeta extraviada?</h4>
				<ul>
				<li><i class="fa fa-square" aria-hidden="true"></i>
					Adquiere la nueva tarjeta en las taquillas de tu central AUS participante más cercana y dala de alta en nuestras taquillas, en www.unidosdesinaloa.com.mx/auscard o en el 01 (800) 6864-367 con tu usuario y contraseña.</li>
				</ul>
				<h4 class="sub-title">¿Puedo transferir mi tarjeta a otra persona?</h4>
				<ul>
				<li><i class="fa fa-square" aria-hidden="true"></i>
					No, la Tarjeta AUSCARD es personal e intransferible.</li>
				</ul>
				<h4 class="sub-title">¿La Tarjeta es válida en cualquier sucursal AUS?</h4>
				<ul>
				<li><i class="fa fa-square" aria-hidden="true"></i>
					Sí, en terminales. (no aplica para puntos de venta).</li>
				</ul>
				<h4 class="sub-title">¿A dónde me puedo comunicar para aclarar dudas sobre mi cuenta, externar una queja u obtener más información sobre el programa de recompensas AUS?</h4>
				<ul>
				<li><i class="fa fa-square" aria-hidden="true"></i>
					Puedes marcar al 01 800 6UNIDOS (864367) o enviar un correo electrónico a atencionaclientes@aussa.com.mx </li>

				</ul>
								</div>
				</div>	
			</div>
		</div>
	</div>
</div>