<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Políticas y obligaciones</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Políticas y obligaciones</a></h4>
			</div>
		</div>
	</div>
</div>
<div class="container" id="politicas-y-obligaciones">
	<div class="row">
		<div class="col-md-12">
			<div class="text">
				<h2 class="title-text">
					Políticas y obligaciones de servicio que presta AUS a sus usuarios.
				</h2>
				<h4 class="sub-title">Descuentos aplicables al usuario.</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> Menores de 0 a 4 años no pagan boleto.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Mayor de 4 a 12 pagan el 50 %</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Personas de la tercera edad 50%</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Los estudiantes y maestros gozaran de una tarifa preferencial durante todo el año.</li>
				</ul>
				<h4 class="sub-title">Promociones permanentes</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> Se aplica descuento en la compra de un viaje redondo, al momento de comprar si boleto en taquilla mismo que tiene un vigencia de 6 meses y deberá ser presentado al momento de viajar y en caso de extravió la empresa no se hace responsable.</li>
				</ul>
				<h4 class="sub-title">Prohibición en cuanto al equipaje.</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> Prohibido viajar con hieleras que contengan líquido. (el traslado de las hieleras con otro tipo de contenido, se dejara a consideración con el personal encargado de la sucursal). </li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Se prohíbe alimentos precederos o con aromas fuertes tales como: mariscos, quesos etc.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Se prohíbe viajar a personas en estado de embriaguez o que presente síntomas de haber consumido algún tipo de droga, la empresa se reserva el derecho de negar la prestación del servicio</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> No se permite viajar con armas de fuego o punzocortantes salvo que se cuente con el permiso legal.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Está prohibido viajar con mascotas dentro del autobús con excepción de las mascotas guías, y dentro del compartimiento se le permitirá siguiendo las reglas que para tal efecto se establezcan.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> No se permite que dentro del equipaje o por separado se lleve aparatos electrónicos en el compartimiento de maletas.</li>
				</ul>
				<h4 class="sub-title">Prohibiciones generales</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> El caso de las mujeres embarazadas cuyo periodo se encuentre en el octavo mes será necesario que la pasajera firme para para la empresa una carta que deslinde a la empresa de cualquier responsabilidad.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> En cuanto a los menores de edad no podrán viajar en los autobuses sin ser acompañados por un adulto y bajo su responsabilidad y resguardo.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Cada pasajero mayor de edad podrá llevar consigo a un menor de edad sin ocupar asiento y en caso que lleve más de un menor el otro pagara la tarifa correspondiente.</li>
				</ul>
				<h4 class="sub-title">Procedimientos y responsabilidad de la empresa en cuanto al equipaje.</h4>
				<ul>
					<li class="sub-sub-title"><span>En cuanto al procedimiento:</span>
						<ul>
							<li><i class="fa fa-square" aria-hidden="true"></i> La entrega del equipaje se realizara al pasajero contra la entrega del ticket en caso contrario no será entregada.</li>
							<li><i class="fa fa-square" aria-hidden="true"></i> Es responsabilidad del usuario exigir y conservar la entrega del ticket ya que en caso de extravío o pérdida la empresa no se hará responsable ni estará obligado para en caso de que persona diferente  recoja su maleta exhibiendo el ticket.</li>
							<li><i class="fa fa-square" aria-hidden="true"></i> Si transporta objetos valiosos así como artículos frágiles so perecederos deberá hacer la manifestación del valor del mismo.</li>
						</ul>
					</li>
					<li class="sub-sub-title"><span>En cuanto a la responsabilidad:</span>
						<ul>
							<li><i class="fa fa-square" aria-hidden="true"></i> Para en caso de pérdida o extravió del equipaje la empresa se responsabiliza a cubrir y así lo expresa en el ticket lo contemplado en el artículo 66 fracción quinta de la ley de caminos puentes y trasporte federal.</li>
							<li><i class="fa fa-square" aria-hidden="true"></i> En caso de pérdida o extravió del boleto de viajero la empresa no se hace responsable de su reembolso y esta queda bajo resguardo y responsabilidad del usuario.</li>
						</ul>
					</li>
				</ul>
				<h4 class="sub-title">Servicio y restricciones en el envío de paquetería, los cuales consisten en:</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> Productos perecederos.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Medicamento controlado.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Líquidos.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Armas de fuego aun las de deporte siempre y cuando no cuenten con autorización oficial de las mismas.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Drogas.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Bebidas etílicas.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Cualquier tipo de animal que no cuente con permiso correspondiente.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Dinero. </li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Documentación fácilmente negociable.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Joyería.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Hieleras cuyo contenido que se encuentren dentro de la primera restricción señalada en el punto relativo a PROHIBICIÓN EN CUANTO AL EQUIPAJE.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Solventes.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Productos flamables.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Refacciones que contengan combustibles o derramen lubricantes.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Baterías para autos.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Pesticidas.</li>

				</ul>
				<h4 class="sub-title">La empresa le proporciona al usuario los siguientes números telefónicos:</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> (667) 761 2900</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> (667) 761 4314</li>
				</ul>
				<h4 class="sub-title">Para en caso de inconformidad o quejas.</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> Por comportamiento inadecuado del operador o cobrador del autobús en que viaja.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Si el operador utiliza el celular sin manos libres, si los baños del autobús se encuentran sucios, el funcionamiento de los televisores se encuentren en óptimas condiciones o cualquier acontecimiento que ponga en peligro la seguridad de los viajeros.</li>
				</ul>
				<h4 class="sub-title">Sistema de facturación.</h4>
				<ul>
					<li><i class="fa fa-square" aria-hidden="true"></i> Mediante instructivo que por medio de folletos que la empresa te proporciona en cada una de sus taquillas de venta.</li>
					<li><i class="fa fa-square" aria-hidden="true"></i> Los boletos manuales se hacen mediante correo electrónico al siguiente aus.recepcion@hotmail.com o en nuestras sucursales de Culiacán y Mazatlán presentando los mismos.</li>
				</ul>
			</div>
		</div>
	</div>
</div>