<div class="container-fluid header-fondo">
	<div class="container">
		<div class="row section-header">
			<div class="col-md-8 section-title">
				<h2>Aviso de privacidad</h2>
			</div>
			<div class="col-md-4 section-link">
				<h4><a href="" title="">Inicio</a> <span>/</span> <a href="" class="active" title="">Aviso de privacidad</a></h4>
			</div>
		</div>
	</div>
</div>

<div class="container" id="aviso-de-privacidad">
	<div class="row">
		<div class="col-md-12">
			<div class="text">
				<p>
					AUTOTRANSPORTES UNIDOS DE SINALOA S.A DE C.V.  En cumplimiento por lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de Particulares, hacen del conocimiento de sus clientes, proveedores, usuarios y Público en general el presente Aviso de Privacidad:
				</p>
				<p>
					Los datos personales que nos proporciona directamente cuando adquiere un boleto en taquillas, telefónicamente, vía internet o en cualquier relación comercial cliente-proveedor, tienen como finalidad referenciar el servicio solicitado, facturación, relación comercial, estudios de mercado o control de calidad; por lo que sus datos personales no serán transferibles a terceros.
				</p>
				<p>
					Su imagen podrá ser video grabada con fines de seguridad, disuasión y prevención del delito. Su imagen se almacenará en el domicilio de la responsable de proteger y resguardar sus datos personales por un término de 48 horas; transcurrido el plazo, las imágenes serán borradas; no podrán ser transferibles a terceros salvo orden judicial.
				</p>
				<p>
					Los datos personales que le solicitamos para los servicios contratados son: nombre y apellidos, domicilio, teléfono, correo electrónico, fecha de nacimiento. Cuando realice algún pago con tarjeta de crédito o débito se requerirán algunos datos financieros: nombre del titular, domicilio, teléfono, nombre de la institución bancaria, número de tarjeta, fecha de vencimiento y código de seguridad. No serán transferibles a terceros.
				</p>
				<p>
					Usted tendrá derecho a acceder, modificar o cancelar todos y cada uno de sus datos, podrá oponerse al uso de ellos e incluso revocarlos. Para hacer valer estos derechos puede contactarnos en el domicilio de la responsable de proteger y resguardar sus datos personales: Oficina Responsable de Protección de Datos Personales de Autotransportes Unidos de Sinaloa S.A. de C.V. con domicilio en Alfonso G. Calderón Velarde S/N interior 15, Código Postal 80020, Culiacán Sinaloa, con Teléfono TEL.   01 (667) 761 29 00
					Y correo electrónico a  atencionaclientes@aussa.com.mx
				</p>
				<p>
					En Caso de alguna modificación al presente Aviso de Privacidad se le dará a conocer a través de las páginas de internet de las empresas, en los módulos de venta, en algún diario de circulación nacional y mediante nuestros operadores telefónicos.
				</p>
				<p>
					 Al adquirir su boleto, contratar alguno de los servicios o establecer una relación comercial con Autotransportes Unidos de Sinaloa s.a. de C.V.
				</p>
			</div>
		</div>
	</div>
	
</div>












